# Multi-run Table 3: seed sweep with ± uncertainties

This runs the ActivitySCOPE pipeline from *More Complicated Workbook - including paper-specific items* `N_RUNS` times on **one copy of the orbit database loaded once**. Only the cross-validation fold assignment and the AutoGluon model seeds change between runs (run *k* uses seed `BASE_SEED + k`). The spread across runs is therefore the model's own run-to-run variability, not day-to-day database changes.

For every run it saves, as soon as the run finishes:
- `run_XXX_final.parquet`: the full `final` frame, with the ΔH sweep columns filled for the rows it was computed on (NaN elsewhere)
- `run_XXX_cometmerge.parquet`: the comet-file frame, with its own ΔH sweep columns
- `run_XXX_table_rows.csv`: the Table 3 values for this run (written last, so it marks the run as complete)
- `run_XXX_meta.json`: seed, timings, validation scores

With `RESUME = True`, re-running the notebook skips completed runs, so a crash overnight costs at most one run. The last section averages all completed runs into Table 3 with mean ± standard deviation for $P(N_{\rm opp}\ge4)$, $\Delta Q$, $S_{\rm EV}$ and $\Delta H$.

The pessimistic second pass (`prob_pessimistic`) is not included.

In [1]:
import os
import gc
import re
import glob
import json
import time
import shutil
import datetime
import tempfile
import traceback
import importlib

import numpy as np
import pandas as pd
from scipy.stats import poisson
from autogluon.tabular import TabularPredictor
import torch
from IPython.display import display

import activityscope_utils as utils
import paper_table
import h_neutrality
importlib.reload(utils)
importlib.reload(paper_table)
importlib.reload(h_neutrality)

WARNING: AstropyDeprecationWarning: The TestRunner class is deprecated and may be removed in a future version.
        Use pytest instead. [astropy.tests.runner]
WARNING: AstropyDeprecationWarning: The TestRunnerBase class is deprecated and may be removed in a future version.
        Use pytest instead. [astropy.utils.decorators]

In [2]:
# PARAMETERS

# Number of training runs and the base seed. Run k uses seed BASE_SEED + k for both the 8-fold
# assignment and the AutoGluon model seeds, so any single run can be reproduced on its own.
N_RUNS = 5
BASE_SEED = 1000

# Per-run outputs and the aggregated table go here. Change RUN_NAME to start a fresh sweep.
RUN_NAME = "table3_seed_sweep"
OUTPUT_DIR = os.path.join("multi_run_outputs", RUN_NAME)

# Skip runs whose outputs already exist, so an interrupted sweep resumes where it stopped.
# Resuming refuses to continue if the loaded database differs from the one the sweep started with.
RESUME = True

# "parquet" (falls back to pickle for a frame Arrow can't store) or "pickle"
SAVE_FORMAT = "parquet"

# The database is loaded ONCE and shared by all runs. If a sweep might be resumed on a later day,
# use the snapshot so the resumed runs see the same data.
use_reproducibility_snapshot = True

# Same modeling parameters as the main workbook
NUM_OPPS_FOR_TRAINING = 4
MIN_ARC_LENGTH_FOR_TRAINING = 20
MIN_NUM_OBS_FOR_TRAINING = 16
TRAINING_TIME_LIMIT = 1700

# Also vary AutoGluon's model seeds from run to run (in addition to the fold assignment).
VARY_MODEL_SEED = True

# False reproduces the main workbook: predictions come from the models refit on all data ("_FULL").
# True keeps the 8 fold models and averages them at inference instead.
USE_BAGGED_INFERENCE = False

# Delete each run's AutoGluon model directory after its outputs are saved.
DELETE_MODELS_AFTER_RUN = True

# Delta-H candidate selection (same as the main workbook; the sweep itself lives in h_neutrality.py)
H_NEUTRALITY_PROBABILITY_MIN = 0.8
H_NEUTRALITY_EXTENSION_DIFFICULTY_MAX = 0.1
H_NEUTRALITY_MAX_OBJECTS = 500
H_NEUTRALITY_MAX_OBJECTS_COMET = 200

extension_difficulty_threshold = 0.9

# Table 3 columns that get a ± (standard deviation across runs), and the decimals for mean and ±.
PM_COLUMNS = ["prob", "DeltaQ", "S_EV", "DeltaH"]
PM_DECIMALS = {"prob": 6, "DeltaQ": 1, "S_EV": 5, "DeltaH": 2, "exp_Num_opps": 1}
NOTES_CSV = "table_notes.csv"

In [3]:
with open('known_active_objects.json', 'r') as f:
    known_strongly_suspected_active_objects = json.load(f)

with open('dual_designation_list.json', 'r') as f:
    dual_designation_list = json.load(f)

discoveries_in_comet_file = ["P/2025 UX109 (Ye)","P/2023 JN16 (Lemmon)","P/2022 BV9 (Lemmon)","P/2017 FL36 (PANSTARRS)","489P/Denning"]

## Load the data once
Same loading, feature engineering, training filters and hard-coded single-opposition overrides as the main workbook. Nothing in this section is repeated per run.

In [4]:
if use_reproducibility_snapshot:
    orb = pd.read_parquet('orb_snapshot.parquet')
else:
    try:
        orb = utils.load_all_databases()
    except Exception as e:
        print(f"Error loading databases: {e}")
        cache_dir = os.path.join(os.getcwd(), '.cache')
        for filename in os.listdir(cache_dir):
            file_path = os.path.join(cache_dir, filename)
            try:
                if os.path.isfile(file_path):
                    os.unlink(file_path)
            except Exception as e:
                print(f"Error deleting file {file_path}: {e}")
        raise Exception(f"Failed to load databases. To fix this, try deleting all files in the cache directory: {cache_dir}. Original error: {e}")

# Pin the date the apparition features treat as "now" (days_since_last_opp, n_detectable, ...) to the
# MPCORB standard epoch -- the latest Epoch in the database, which is what the features themselves
# auto-detect, and what the main workbook pins after loading. Left unpinned, every feature_engineering
# call picks the latest Epoch in its own frame: the comet file (Epoch = perihelion time) lands around
# 2092, and each single-object Delta-H sweep frame uses that object's own epoch.
REFERENCE_EPOCH_JD = utils.catalogue_reference_epoch(orb)
utils.set_reference_epoch(REFERENCE_EPOCH_JD)
print(f"reference epoch for apparition features: JD {REFERENCE_EPOCH_JD}")

# Fingerprint of the loaded database, used to stop a resumed sweep from mixing in different data
database_fingerprint = {
    "reference_epoch_jd": REFERENCE_EPOCH_JD,
    "n_rows": int(len(orb)),
    "num_opps_sum": int(pd.to_numeric(orb["Num_opps"], errors="coerce").fillna(0).sum()),
    "num_obs_sum": int(pd.to_numeric(orb["Num_obs"], errors="coerce").fillna(0).sum()),
}
print(database_fingerprint)

orb = utils.feature_engineering(orb)

extension_difficulty = pd.read_csv("extension_difficulty.csv")
orb = orb.merge(extension_difficulty, on="Principal_desig", how="left")

reference epoch for apparition features: JD 2461200.5
{'reference_epoch_jd': 2461200.5, 'n_rows': 1563218, 'num_opps_sum': 14293681, 'num_obs_sum': 527618579}

In [5]:
orb_training = orb[((orb["Arc_length"]>=MIN_ARC_LENGTH_FOR_TRAINING)|(orb["Arc_length"].isna())|(orb["Perihelion_dist"]<1.3))
                       &(orb["Num_obs"]>=MIN_NUM_OBS_FOR_TRAINING)
                       &~orb["filtered_out"].astype(bool)
                       &(orb["a_diff_abs"]<0.0005)
                       &(orb["e_diff_abs"]<0.00015)
                       &(orb["i_diff_abs"]<0.003)
                       &(orb["multi_opp_disagree"]==0)
                       &((orb["extension_difficulty"]<0.1)| (orb["extension_difficulty"].isna())|(orb["Perihelion_dist"]<1.3))
                       &((orb["U"]<9)|(orb["Perihelion_dist"]<1.3))
                       &~orb["Principal_desig"].isin(known_strongly_suspected_active_objects)
                       &~orb["Number"].isin(dual_designation_list)]

print(f"Total objects in orbit database: {len(orb)}")
print(f"Total objects in decent orbit database: {len(orb_training)}")

mlcols = ['H', 'Node', 'a', 'i', 'vis_q',
          'Perihelion_direction_x_e', 'Perihelion_direction_y_e',
          'days_since_last_opp',
          'n_detectable', 'n_detectable_var', 'years_since_first_detectable', 'days_since_last_detectable',
       'Is_Past_Threshold']
mlcols_reg = mlcols.copy()
mlcols_reg.remove("Is_Past_Threshold")
mlcols_reg.append("Num_opps_minus_one")

# Fold assignments are added per run
data_df = orb_training.dropna(subset=["H"])[mlcols].astype(np.float32)
data_df_reg = orb_training.dropna(subset=["H"])[mlcols_reg].astype(np.float32)

# Hard code both 2009 DP2 and 2024 XE22 to Num_opps = 1 with Arc_length of 22 (main workbook cell "Hard code both...")
orb.loc[orb["Principal_desig"]=="2009 DP2", "Num_opps"] = 1
orb.loc[orb["Principal_desig"]=="2024 XE22", "Num_opps"] = 1
orb.loc[orb["Principal_desig"]=="2009 DP2", "Arc_length"] = 22
orb.loc[orb["Principal_desig"]=="2024 XE22", "Arc_length"] = 22

# Prediction frame before any model output; copied at the start of every run
orb_pred_base = orb.dropna(subset=["H_MPC","H_astdys","H_jpl"], how='all').copy()
orb_pred_base = utils.apply_nights_overrides(orb_pred_base)
orb_pred_base = utils.apply_magnitude_corrections(orb_pred_base)

Total objects in orbit database: 1563218
Total objects in decent orbit database: 1377035

In [6]:
# Comet orbit file (main workbook "Import the Comet Orbit File from MPC"), feature-engineered once
comet = pd.read_json("allcometels.json.gz",compression='gzip')
comet = comet[comet["Orbit_type"].isin(["P","D","A"])]

comet["a"] = comet["Perihelion_dist"] / (1 - comet["e"])
comet["Orbital_period"] = np.sqrt(comet["a"]**3)


def calc_jd(year, month, day):
    y = year.copy()
    m = month.copy()
    mask = m <= 2
    y[mask] -= 1
    m[mask] += 12
    A = np.floor(y / 100)
    B = 2 - A + np.floor(A / 4)
    B[y < 1582] = 0
    B[(y == 1582) & (month < 10)] = 0
    B[(y == 1582) & (month == 10) & (day <= 4)] = 0
    return np.floor(365.25 * (y + 4716)) + np.floor(30.6001 * (m + 1)) + day + B - 1524.5

comet["Tp"] = calc_jd(comet["Year_of_perihelion"], comet["Month_of_perihelion"], comet["Day_of_perihelion"])
comet["Epoch"] = comet["Tp"]
comet["M"] = 0.0

comet_mags_fo = pd.read_fwf("./comet_orbits/comet_els_fo.txt", widths=[8, 5, 1000], names=["Packed", "Mag", "Discard"])

comet["fullpacked"] = comet["Orbit_type"] + comet["Provisional_packed_desig"]
comet.drop(columns=["H"], inplace=True, errors="ignore") # Wrong H! This is the comet H and not the inert asteroidal H
cometmerge_base = comet.merge(comet_mags_fo, left_on="fullpacked", right_on="Packed", how="left")

cometmerge_base.loc[cometmerge_base["Designation_and_name"] == "489P/Denning", "Mag"] = 15.35
cometmerge_base.loc[cometmerge_base["Designation_and_name"] == "P/2025 UX109 (Ye)", "Mag"] = 15.00

cometmerge_base["H"] = cometmerge_base["Mag"]
assert utils._reference_epoch(cometmerge_base) == REFERENCE_EPOCH_JD, "reference epoch not pinned; run the data-loading cell first"
cometmerge_base = utils.feature_engineering(cometmerge_base)

/Users/petervw/mambaforge/envs/actscope-16/lib/python3.11/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/petervw/GitHub/ActivitySCOPE/activityscope_utils.py:2050: RuntimeWarning: invalid value encountered in sqrt
  sqrt_1pe, sqrt_1me = col(np.sqrt(1.0 + e)), col(np.sqrt(1.0 - e))

In [7]:
# Table 3 objects. Every one of them gets a Delta-H in every run, whatever that run's candidate ranking.
table_notes = paper_table.load_notes(NOTES_CSV)


def notes_designation_to_principal(designation):
    """'362P/(457175) 2008 GO98' -> '2008 GO98' (comet prefix and number stripped)."""
    return re.sub(r"^\(\d+\)\s+", "", paper_table._COMET_PREFIX_RE.sub("", designation))


_orb_desigs = set(orb["Principal_desig"])
table_orbit_desigs = [d for d in (notes_designation_to_principal(r["designation"]) for r in table_notes) if d in _orb_desigs]
_comet_names = set(cometmerge_base["Designation_and_name"])
table_comet_names = [r["designation"] for r in table_notes if r["designation"] in _comet_names]
_unresolved = [r["designation"] for r in table_notes
               if notes_designation_to_principal(r["designation"]) not in _orb_desigs and r["designation"] not in _comet_names]
print(f"Table 3 objects: {len(table_orbit_desigs)} in the orbit database, {len(table_comet_names)} in the comet file")
if _unresolved:
    print("WARNING: not found in either source (no Delta-H will be forced for these):", _unresolved)

Table 3 objects: 19 in the orbit database, 5 in the comet file

## One run
Each step mirrors the main workbook; the section it comes from is named in the comments.

In [8]:
save_path = os.path.join(tempfile.gettempdir(), 'activityscope_ag_multi')

# There's a known issue where torch probability calibration dies sometimes with multiple threads. This is a workaround.
torch.set_num_threads(1)

TABLE_SOURCE_COLS = ["Object", "q", "a", "e", "i", "H", "TJ", "Num_opps", "exp_Num_opps", "prob",
                     "quantile_Opps", "DeltaQ", "poisson_cdf", "H_change_to_neutral"]
TABLE_VALUE_COLS = paper_table.DATA_COLUMNS + ["DeltaH"]


def fit_kwargs(seed):
    ensemble_args = {"fold_fitting_strategy": "sequential_local"}
    if VARY_MODEL_SEED:
        ensemble_args.update({"model_random_seed": int(seed), "vary_seed_across_folds": True})
    kwargs = dict(presets="good_quality", num_bag_folds=8, dynamic_stacking=False,
                  ag_args_ensemble=ensemble_args, time_limit=TRAINING_TIME_LIMIT/3)
    if USE_BAGGED_INFERENCE:
        kwargs.update(refit_full=False, set_best_to_refit_full=False, save_bag_folds=True)
    return kwargs


def with_oof(full_pred, oof_pred):
    """Predictions for every row, replaced by the out-of-fold prediction wherever the row was in training."""
    out = pd.Series(np.asarray(full_pred, dtype=float), index=full_pred.index)
    common = out.index.intersection(oof_pred.index)
    out.loc[common] = np.asarray(oof_pred.loc[common], dtype=float)
    return out


def getFinal(orb_pred):
    final = orb_pred.copy()
    final.rename(columns={"Perihelion_dist":"q","Aphelion_dist":"Q"},inplace=True)
    final.set_index("Principal_desig", inplace=True)
    final['DeltaQ'] = final["quantile_Opps"]-final["Num_opps"]
    final.sort_values("DeltaQ",ascending=False, inplace=True)
    final["Known / Strong Suspect"] = final.index.isin(known_strongly_suspected_active_objects)
    return final


def table_rows_for_run(final, cometmerge):
    """Table 3 values for one run, computed exactly as paper_table does (including the dagger single-opposition rows)."""
    for_paper = final[[c for c in ["Number"] + TABLE_SOURCE_COLS if c in final.columns]].copy()
    for_paper["Principal_desig"] = for_paper.index
    for_paper["Object"] = for_paper["Number"].astype(str) + " " + for_paper["Principal_desig"]
    for_paper["Object"] = for_paper["Object"].str.replace("<NA> ", "")

    comet = cometmerge.rename(columns={"Designation_and_name": "Object"})
    frames = [df[[c for c in TABLE_SOURCE_COLS if c in df.columns]] for df in (for_paper, comet)]
    combined = pd.concat(frames, ignore_index=True)
    combined["DeltaH"] = pd.to_numeric(combined["H_change_to_neutral"], errors="coerce")
    combined = paper_table._ensure_derived(combined)
    by_object = combined.drop_duplicates(subset="Object").set_index("Object")

    rows = []
    for r in table_notes:
        data = paper_table._lookup(by_object, r["designation"])
        found = data is not None
        if r["nopp_dagger"]:
            data = paper_table._as_single_opp(data)
        rows.append({"designation": r["designation"], "found": found,
                     **{c: paper_table._num(data, c) for c in TABLE_VALUE_COLS}})
    return pd.DataFrame(rows)


def save_frame(df, stem):
    if SAVE_FORMAT == "parquet":
        path = stem + ".parquet"
        try:
            df.to_parquet(path)
            return path
        except Exception as e:
            print(f"  parquet failed for {os.path.basename(stem)} ({type(e).__name__}: {e}); saving as pickle")
            if os.path.exists(path):
                os.remove(path)
    path = stem + ".pkl"
    df.to_pickle(path)
    return path

In [9]:
def run_once(run_idx):
    seed = BASE_SEED + run_idx
    stem = os.path.join(OUTPUT_DIR, f"run_{run_idx:03d}")
    run_model_path = os.path.join(save_path, f"{RUN_NAME}_run{run_idx:03d}_{datetime.datetime.now():%Y%m%d_%H%M%S}")
    timings = {}
    t0 = time.time()
    utils.set_reference_epoch(REFERENCE_EPOCH_JD)  # the Delta-H sweep frames would otherwise each pick their own epoch
    try:
        # ---- Modeling (main workbook "Modeling"), with this run's folds and seeds ----
        d_bin = data_df.copy()
        d_reg = data_df_reg.copy()
        shared_folds = np.random.default_rng(seed).integers(0, 8, size=len(d_bin))
        d_bin["Shared_Fold"] = shared_folds
        d_reg["Shared_Fold"] = shared_folds

        predictor_reg = TabularPredictor(label="Num_opps_minus_one", groups="Shared_Fold", eval_metric=utils.POISSON_SCORER, problem_type='regression', path=os.path.join(run_model_path, "reg"))
        predictor_reg.fit(d_reg, hyperparameters=utils.HYPERPARAMETERS_POISSON, num_stack_levels=0, **fit_kwargs(seed))
        d_bin["exp_Num_opps"] = with_oof(predictor_reg.predict(d_bin) + 1, TabularPredictor.predict_oof(predictor_reg) + 1)
        d_reg["exp_Num_opps"] = d_bin["exp_Num_opps"]

        predictor_quant = TabularPredictor(label="Num_opps_minus_one", groups="Shared_Fold", problem_type='quantile', quantile_levels=[0.006], path=os.path.join(run_model_path, "quant"))
        predictor_quant.fit(d_reg, hyperparameters=utils.HYPERPARAMETERS_QUANTILE, num_stack_levels=1, **fit_kwargs(seed))
        d_bin["quantile_Opps"] = with_oof(predictor_quant.predict(d_bin)[0.006] + 1, TabularPredictor.predict_oof(predictor_quant)[0.006] + 1)

        predictor = TabularPredictor(label="Is_Past_Threshold", groups="Shared_Fold", eval_metric='log_loss', path=os.path.join(run_model_path, "bin"))
        predictor.fit(d_bin, hyperparameters=utils.HYPERPARAMETERS_BINARY, num_stack_levels=0, **fit_kwargs(seed))
        timings["training_s"] = time.time() - t0

        # ---- Predictions (main workbook "Make Predictions") ----
        t = time.time()
        orb_pred = orb_pred_base.copy()
        orb_pred["exp_Num_opps"] = with_oof(predictor_reg.predict(orb_pred) + 1, TabularPredictor.predict_oof(predictor_reg) + 1)
        orb_pred["quantile_Opps"] = with_oof(predictor_quant.predict(orb_pred)[0.006] + 1, TabularPredictor.predict_oof(predictor_quant)[0.006] + 1)
        orb_pred["prob"] = with_oof(predictor.predict_proba(orb_pred)[1], TabularPredictor.predict_proba_oof(predictor)[1])
        orb_pred["poisson_cdf"] = poisson.cdf(orb_pred["Num_opps"]-1, orb_pred["exp_Num_opps"]-1)

        final = getFinal(orb_pred)

        # ---- Extension difficulty classifier, then drop filtered objects ----
        orb_pred, final = utils.train_extension_difficulty_classifier(orb_pred, final, orb)
        orb_pred = orb_pred[~orb_pred["filtered_out"].astype(bool)]
        final = final[~final["filtered_out"].astype(bool)].copy()
        timings["predictions_s"] = time.time() - t

        # ---- Centralized ranking (main workbook "Centralized Ranking") ----
        final["priority_score"] = final["DeltaQ"] - (final["extension_difficulty"] * 15.5)
        combined_rankings = final[(((final["Arc_length"]>=8)|(final["Arc_length"].isna()))
              &(final["Num_obs"]>=6)
              &((final["Num_obs"]>=7)|(final["nights_total"]>=5))
              &(final["DeltaQ"]>0.3*final["quantile_Opps"])
              &(final["prob"]>0.9)
              &(final["q"]>1.1)
              &((final["extension_difficulty"].between(0,extension_difficulty_threshold))|(final["nights_total"].isna()))
              &(final["Orbital_period"]<20))| final.index.isin(known_strongly_suspected_active_objects)].copy()
        combined_rankings.sort_values("priority_score", ascending=False, inplace=True)

        # ---- Delta-H, orbit database (h_neutrality.py, same candidates as the main workbook plus Table 3) ----
        t = time.time()
        h_candidates = combined_rankings[
            (combined_rankings["prob"] >= H_NEUTRALITY_PROBABILITY_MIN)
            & (combined_rankings["extension_difficulty"] <= H_NEUTRALITY_EXTENSION_DIFFICULTY_MAX)
            & combined_rankings["Num_opps"].notna()
        ].head(H_NEUTRALITY_MAX_OBJECTS)
        # also the known/strongly suspected active objects and every Table 3 object
        forced = final.loc[final.index.intersection(pd.Index(list(known_strongly_suspected_active_objects) + table_orbit_desigs))]
        h_candidates = pd.concat([h_candidates, forced])
        h_candidates = h_candidates[~h_candidates.index.duplicated(keep="first")]
        h_candidates = h_candidates[h_candidates["Num_opps"].notna() & h_candidates["H"].notna()]
        dh_orbit = h_neutrality.delta_h_sweep(h_candidates, predictor_reg)
        h_neutrality.attach_delta_h(final, dh_orbit, final.index)

        # ---- Comet file predictions and Delta-H (main workbook comet cells) ----
        cometmerge = cometmerge_base.copy()
        cometmerge["exp_Num_opps"] = predictor_reg.predict(cometmerge) + 1
        cometmerge["quantile_Opps"] = predictor_quant.predict(cometmerge)[0.006] + 1
        cometmerge["prob"] = predictor.predict_proba(cometmerge)[1]
        cometmerge["Num_opps"] = pd.NA # no data for this in the comet file
        cometmerge.loc[cometmerge["Designation_and_name"].isin(discoveries_in_comet_file), "Num_opps"] = 1
        cometmerge["Num_opps"] = cometmerge["Num_opps"].astype("Int64")
        num_opps = pd.to_numeric(cometmerge["Num_opps"], errors="coerce")
        exp_num_opps = pd.to_numeric(cometmerge["exp_Num_opps"], errors="coerce")
        cometmerge["poisson_cdf"] = pd.Series(poisson.cdf(num_opps - 1, exp_num_opps - 1), index=cometmerge.index, dtype="Float64")
        cometmerge['DeltaQ'] = cometmerge["quantile_Opps"]-cometmerge["Num_opps"]
        cometmerge.rename(columns={"Perihelion_dist":"q","Aphelion_dist":"Q"},inplace=True)

        comet_candidates = cometmerge[cometmerge["H"].notna()].sort_values("prob", ascending=False).head(H_NEUTRALITY_MAX_OBJECTS_COMET)
        comet_forced = cometmerge[cometmerge["Designation_and_name"].isin(set(discoveries_in_comet_file) | set(table_comet_names))
                                  & cometmerge["H"].notna()]
        comet_candidates = pd.concat([comet_candidates, comet_forced]).set_index("Designation_and_name", drop=False)
        comet_candidates = comet_candidates[~comet_candidates.index.duplicated(keep="first")]
        dh_comet = h_neutrality.delta_h_sweep(comet_candidates, predictor_reg, observed_num_opps=1.0)
        h_neutrality.attach_delta_h(cometmerge, dh_comet, cometmerge["Designation_and_name"])
        timings["delta_h_s"] = time.time() - t

        # ---- Save ----
        t = time.time()
        rows = table_rows_for_run(final, cometmerge)
        rows.insert(0, "run", run_idx)
        rows.insert(1, "seed", seed)
        paths = {"final": save_frame(final, stem + "_final"),
                 "cometmerge": save_frame(cometmerge, stem + "_cometmerge")}
        timings["save_s"] = time.time() - t
        timings["total_s"] = time.time() - t0

        meta = {
            "run": run_idx, "seed": seed, "finished": datetime.datetime.now().isoformat(timespec="seconds"),
            "timings_s": timings, "files": paths,
            "n_delta_h_orbit": int(len(dh_orbit)), "n_delta_h_comet": int(len(dh_comet)),
            "model_best": {name: p.model_best for name, p in [("reg", predictor_reg), ("quant", predictor_quant), ("bin", predictor)]},
            "score_val": {name: p.leaderboard(silent=True).set_index("model")["score_val"].dropna().to_dict()
                          for name, p in [("reg", predictor_reg), ("quant", predictor_quant), ("bin", predictor)]},
        }
        with open(stem + "_meta.json", "w") as f:
            json.dump(meta, f, indent=2, default=str)
        rows.to_csv(stem + "_table_rows.csv", index=False)  # written last: marks the run complete for RESUME

        missing = rows.loc[~rows["found"], "designation"].tolist()
        if missing:
            print(f"  WARNING: Table 3 objects with no data this run: {missing}")
        return rows
    finally:
        gc.collect()
        if DELETE_MODELS_AFTER_RUN:
            shutil.rmtree(run_model_path, ignore_errors=True)

## Run the sweep

In [10]:
os.makedirs(OUTPUT_DIR, exist_ok=True)

params_path = os.path.join(OUTPUT_DIR, "sweep_parameters.json")
sweep_parameters = {
    "N_RUNS": N_RUNS, "BASE_SEED": BASE_SEED, "use_reproducibility_snapshot": use_reproducibility_snapshot,
    "TRAINING_TIME_LIMIT": TRAINING_TIME_LIMIT, "VARY_MODEL_SEED": VARY_MODEL_SEED,
    "USE_BAGGED_INFERENCE": USE_BAGGED_INFERENCE, "H_NEUTRALITY_MAX_OBJECTS": H_NEUTRALITY_MAX_OBJECTS,
    "H_NEUTRALITY_MAX_OBJECTS_COMET": H_NEUTRALITY_MAX_OBJECTS_COMET, "database_fingerprint": database_fingerprint,
}
if os.path.exists(params_path) and glob.glob(os.path.join(OUTPUT_DIR, "run_*_table_rows.csv")):
    with open(params_path) as f:
        previous = json.load(f)
    if previous.get("database_fingerprint") != database_fingerprint:
        raise RuntimeError(
            f"{OUTPUT_DIR} already has runs made on a different database ({previous.get('database_fingerprint')} vs "
            f"{database_fingerprint}). Use a new RUN_NAME, or load the same data, so runs aren't mixed.")
with open(params_path, "w") as f:
    json.dump(sweep_parameters, f, indent=2, default=str)

sweep_start = time.time()
for run_idx in range(N_RUNS):
    if RESUME and os.path.exists(os.path.join(OUTPUT_DIR, f"run_{run_idx:03d}_table_rows.csv")):
        print(f"run {run_idx}: already complete, skipping")
        continue
    print(f"\n===== run {run_idx + 1} of {N_RUNS} (seed {BASE_SEED + run_idx}), started {datetime.datetime.now():%Y-%m-%d %H:%M} =====")
    t = time.time()
    try:
        run_once(run_idx)
        print(f"===== run {run_idx + 1} of {N_RUNS} done in {(time.time() - t) / 60:.1f} min =====")
    except Exception:
        # Keep going so one failure doesn't cost the rest of the night; the traceback is saved next to the outputs.
        err = traceback.format_exc()
        print(err)
        with open(os.path.join(OUTPUT_DIR, f"run_{run_idx:03d}_error.txt"), "w") as f:
            f.write(err)
print(f"\nsweep finished in {(time.time() - sweep_start) / 3600:.2f} h")

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       8.74 GB / 32.00 GB (27.3%)
Disk Space Avail:   3.37 GB / 926.35 GB (0.4%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================

===== run 1 of 5 (seed 1000), started 2026-09-30 09:18 =====

Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.

Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run000_20260930_091817/reg"
Train Data Rows:    1377032
Train Data Columns: 13
Label Column:       Num_opps_minus_one
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8963.80 MB
	Train Data (Original)  Memory Usage: 63.04 MB (0.7% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 12 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 12 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.2s = Fit runtime
	12 features in original data used to generate 12 features in processed data.
	Train Data (Processed) Memory Usage: 63.04 MB (0.7% of available memory)
Data preprocessing and feature engineering runtime = 1.31s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_poisson_deviance'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'objective': 'poisson', 'num_iterations': 1000, 'learning_rate': 0.1}],
	'XGB': [{'objective': 'count:poisson'}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 565.36s of the 565.35s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)

[1000]	valid_set's poisson: -13.2477	valid_set's mean_poisson_deviance: -0.383516
[1000]	valid_set's poisson: -13.2117	valid_set's mean_poisson_deviance: -0.388538
[1000]	valid_set's poisson: -13.2132	valid_set's mean_poisson_deviance: -0.384733
[1000]	valid_set's poisson: -13.3092	valid_set's mean_poisson_deviance: -0.384205
[1000]	valid_set's poisson: -13.2695	valid_set's mean_poisson_deviance: -0.382975
[1000]	valid_set's poisson: -13.1957	valid_set's mean_poisson_deviance: -0.384636
[1000]	valid_set's poisson: -13.2664	valid_set's mean_poisson_deviance: -0.385501
[1000]	valid_set's poisson: -13.2095	valid_set's mean_poisson_deviance: -0.381962

	-0.3845	 = Validation score   (-mean_poisson_deviance)
	179.32s	 = Training   runtime
	56.55s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 327.70s of the 327.70s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.3899	 = Validation score   (-mean_poisson_deviance)
	308.75s	 = Training   runtime
	6.32s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 10.78s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/7.1 GB
	Ensemble Weights: {'LightGBM_BAG_L1': 1.0}
	-0.3845	 = Validation score   (-mean_poisson_deviance)
	0.69s	 = Training   runtime
	0.02s	 = Validation runtime
AutoGluon training complete, total runtime = 558.49s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 3043.5 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.4/6.9 GB
	16.86s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0
	31.2s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBM_BAG_L1': 1.0}
	0.69s	 = Training   runtime
Updated best model to "LightGBM_BAG_L1_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "LightGBM_BAG_L1_FULL" for predict() and predict_proba().
Refit complete, total runtime = 50.9s ... Best model: "LightGBM_BAG_L1_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run000_20260930_091817/reg")
Using OOF from "LightGBM_BAG_L1" as a proxy for "LightGBM_BAG_L1_FULL".
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       7.00 GB / 32.00 GB (21.9%)
Disk Space Avail:   4.11 GB / 926.35 GB (0.4%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run000_20260930_091817/quant"
Train Data Rows:    1377032
Train Data Columns: 14
Label Column:       Num_opps_minus_one
Problem Type:       quantile
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    7264.87 MB
	Train Data (Original)  Memory Usage: 73.54 MB (1.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 13 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 13 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.4s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 73.54 MB (1.0% of available memory)
Data preprocessing and feature engineering runtime = 1.53s ...
AutoGluon will gauge predictive performance using evaluation metric: 'pinball_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'XGB': [{}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 3 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 376.66s of the 565.13s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 1834. Best iteration is:
	[1834]	valid_set's quantile: 0.0234733
	Time limit exceeded... Skipping LightGBMXT_BAG_L1.
Fitting model: LightGBM_BAG_L1 ... Training model for up to 323.68s of the 512.15s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.0292	 = Validation score   (-pinball_loss)
	165.59s	 = Training   runtime
	20.89s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 135.37s of the 323.84s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 238. Best iteration is:
	[238]	valid_set's quantile: 0.0267053
	Ran out of time, early stopping on iteration 243. Best iteration is:
	[243]	valid_set's quantile: 0.0263625
	Ran out of time, early stopping on iteration 260. Best iteration is:
	[260]	valid_set's quantile: 0.0261354
	Ran out of time, early stopping on iteration 202. Best iteration is:
	[202]	valid_set's quantile: 0.028975
	Ran out of time, early stopping on iteration 197. Best iteration is:
	[197]	valid_set's quantile: 0.0283961
	Ran out of time, early stopping on iteration 232. Best iteration is:
	[232]	valid_set's quantile: 0.026296
	Ran out of time, early stopping on iteration 225. Best iteration is:
	[225]	valid_set's quantile: 0.0270971
	Ran out of time, early stopping on iteration 221. Best iteration is:
	[221]	valid_set's quantile: 0.0266327
	-0.0271	 = Validation score   (-pinball_loss)
	119.09s	 = Training   runtime
	12.87s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 189.81s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/5.8 GB
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	-0.0271	 = Validation score   (-pinball_loss)
	1.08s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting 3 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 188.34s of the 188.31s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 465. Best iteration is:
	[465]	valid_set's quantile: 0.0236798
	Time limit exceeded... Skipping LightGBMXT_BAG_L2.
Fitting model: LightGBM_BAG_L2 ... Training model for up to 163.86s of the 163.83s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 484. Best iteration is:
	[473]	valid_set's quantile: 0.0280223
	Ran out of time, early stopping on iteration 506. Best iteration is:
	[506]	valid_set's quantile: 0.027089
	Ran out of time, early stopping on iteration 571. Best iteration is:
	[543]	valid_set's quantile: 0.0304803
	Ran out of time, early stopping on iteration 734. Best iteration is:
	[612]	valid_set's quantile: 0.0278573
	Ran out of time, early stopping on iteration 954. Best iteration is:
	[803]	valid_set's quantile: 0.0278755
	Ran out of time, early stopping on iteration 978. Best iteration is:
	[978]	valid_set's quantile: 0.0279172
	-0.0284	 = Validation score   (-pinball_loss)
	142.24s	 = Training   runtime
	18.59s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the 1.48s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/6.5 GB
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	-0.0271	 = Validation score   (-pinball_loss)
	1.19s	 = Training   runtime
	0.03s	 = Validation runtime
AutoGluon training complete, total runtime = 566.83s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 13372.3 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/6.5 GB
	15.07s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMLarge_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/6.5 GB
	11.29s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	1.08s	 = Training   runtime
Fitting 1 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L2_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/6.5 GB
	14.37s	 = Training   runtime
Fitting model: WeightedEnsemble_L3_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	1.19s	 = Training   runtime
Updated best model to "LightGBMLarge_BAG_L1_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "LightGBMLarge_BAG_L1_FULL" for predict() and predict_proba().
Refit complete, total runtime = 42.53s ... Best model: "LightGBMLarge_BAG_L1_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run000_20260930_091817/quant")
Using OOF from "LightGBMLarge_BAG_L1" as a proxy for "LightGBMLarge_BAG_L1_FULL".
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       6.67 GB / 32.00 GB (20.8%)
Disk Space Avail:   5.18 GB / 926.35 GB (0.6%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run000_20260930_091817/bin"
Train Data Rows:    1377032
Train Data Columns: 15
Label Column:       Is_Past_Threshold
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float32(1.0), np.float32(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6952.16 MB
	Train Data (Original)  Memory Usage: 84.05 MB (1.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 14 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 14 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.4s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 84.05 MB (1.2% of available memory)
Data preprocessing and feature engineering runtime = 1.55s ...
AutoGluon will gauge predictive performance using evaluation metric: 'log_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'XGB': [{}, {'learning_rate': 0.5, 'max_depth': 3, 'min_child_weight': 18, 'subsample': 1.0, 'ag_args': {'name_suffix': '_tuned'}}],
}
Fitting 4 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 565.11s of the 565.11s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)

[1000]	valid_set's binary_logloss: 0.148866
[2000]	valid_set's binary_logloss: 0.148737
[3000]	valid_set's binary_logloss: 0.148778
[1000]	valid_set's binary_logloss: 0.148819
[2000]	valid_set's binary_logloss: 0.148586

	-0.148	 = Validation score   (-log_loss)
	125.07s	 = Training   runtime
	29.15s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 409.67s of the 409.67s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.147	 = Validation score   (-log_loss)
	348.16s	 = Training   runtime
	6.89s	 = Validation runtime
Fitting model: XGBoost_tuned_BAG_L1 ... Training model for up to 52.35s of the 52.35s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.1483	 = Validation score   (-log_loss)
	48.64s	 = Training   runtime
	0.89s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 0.87s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/6.1 GB
	Ensemble Weights: {'XGBoost_BAG_L1': 0.812, 'LightGBM_BAG_L1': 0.188}
	-0.1469	 = Validation score   (-log_loss)
	1.23s	 = Training   runtime
	0.03s	 = Validation runtime
AutoGluon training complete, total runtime = 568.34s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4775.2 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.6/6.0 GB
	13.69s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0
	27.73s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_tuned_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0
	5.25s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'XGBoost_BAG_L1': 0.812, 'LightGBM_BAG_L1': 0.188}
	1.23s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 51.25s ... Best model: "WeightedEnsemble_L2_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run000_20260930_091817/bin")
Using OOF from "LightGBM_BAG_L1" as a proxy for "LightGBM_BAG_L1_FULL".
Using OOF from "LightGBMLarge_BAG_L1" as a proxy for "LightGBMLarge_BAG_L1_FULL".
Using OOF from "WeightedEnsemble_L2" as a proxy for "WeightedEnsemble_L2_FULL".

Positive examples from filter list: 43
Positive examples from multi-opp mislinkages: 96
Positive examples (high extension difficulty): 1741
Negative examples (low extension difficulty): 456801
Training set after refinement: 457781

/Users/petervw/GitHub/ActivitySCOPE/activityscope_utils.py:2050: RuntimeWarning: invalid value encountered in sqrt
  sqrt_1pe, sqrt_1me = col(np.sqrt(1.0 + e)), col(np.sqrt(1.0 - e))

  parquet failed for run_000_final (OSError: [Errno 28] Error writing bytes to file. Detail: [errno 28] No space left on device); saving as pickle
Traceback (most recent call last):
  File "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/ipykernel_15618/4115635105.py", line 28, in <module>
    run_once(run_idx)
  File "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/ipykernel_15618/915795175.py", line 100, in run_once
    paths = {"final": save_frame(final, stem + "_final"),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/ipykernel_15618/2559230349.py", line 76, in save_frame
    df.to_pickle(path)
  File "/Users/petervw/mambaforge/envs/actscope-16/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petervw/mambaforge/envs/actscope-16/lib/python3.11/site-packages/pandas/core/generic.py", line 3187, in to_pickle
    to_pickle(
  File "/Users/petervw/mambaforge/envs/actscope-16/lib/python3.11/site-packages/pandas/io/pickle.py", line 103, in to_pickle
    with get_handle(
         ^^^^^^^^^^^
  File "/Users/petervw/mambaforge/envs/actscope-16/lib/python3.11/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] No space left on device: 'multi_run_outputs/table3_seed_sweep/run_000_final.pkl'


===== run 2 of 5 (seed 1001), started 2026-09-30 09:54 =====

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       8.72 GB / 32.00 GB (27.3%)
Disk Space Avail:   1.31 GB / 926.35 GB (0.1%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run001_20260930_095418/reg"
Train Data Rows:    1377032
Train Data Columns: 13
Label Column:       Num_opps_minus_one
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8983.43 MB
	Train Data (Original)  Memory Usage: 63.04 MB (0.7% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 12 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 12 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.7s = Fit runtime
	12 features in original data used to generate 12 features in processed data.
	Train Data (Processed) Memory Usage: 63.04 MB (0.7% of available memory)
Data preprocessing and feature engineering runtime = 1.77s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_poisson_deviance'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'objective': 'poisson', 'num_iterations': 1000, 'learning_rate': 0.1}],
	'XGB': [{'objective': 'count:poisson'}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 564.89s of the 564.89s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 603. Best iteration is:
	[603]	valid_set's poisson: -13.2162	valid_set's mean_poisson_deviance: -0.392178
	Ran out of time, early stopping on iteration 450. Best iteration is:
	[450]	valid_set's poisson: -13.2099	valid_set's mean_poisson_deviance: -0.390853
	Ran out of time, early stopping on iteration 882. Best iteration is:
	[882]	valid_set's poisson: -13.2794	valid_set's mean_poisson_deviance: -0.384434

[1000]	valid_set's poisson: -13.2507	valid_set's mean_poisson_deviance: -0.386229
[1000]	valid_set's poisson: -13.2327	valid_set's mean_poisson_deviance: -0.384697
[1000]	valid_set's poisson: -13.1976	valid_set's mean_poisson_deviance: -0.381936
[1000]	valid_set's poisson: -13.2354	valid_set's mean_poisson_deviance: -0.383878
[1000]	valid_set's poisson: -13.2945	valid_set's mean_poisson_deviance: -0.384331

	-0.3861	 = Validation score   (-mean_poisson_deviance)
	358.15s	 = Training   runtime
	54.26s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 151.17s of the 151.16s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.4194	 = Validation score   (-mean_poisson_deviance)
	153.68s	 = Training   runtime
	2.53s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the -6.09s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/7.3 GB
	Ensemble Weights: {'LightGBM_BAG_L1': 1.0}
	-0.3861	 = Validation score   (-mean_poisson_deviance)
	0.8s	 = Training   runtime
	0.02s	 = Validation runtime
AutoGluon training complete, total runtime = 573.83s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 3172.2 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.4/7.3 GB
	20.47s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0
	14.69s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBM_BAG_L1': 1.0}
	0.8s	 = Training   runtime
Updated best model to "LightGBM_BAG_L1_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "LightGBM_BAG_L1_FULL" for predict() and predict_proba().
Refit complete, total runtime = 36.39s ... Best model: "LightGBM_BAG_L1_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run001_20260930_095418/reg")
Using OOF from "LightGBM_BAG_L1" as a proxy for "LightGBM_BAG_L1_FULL".
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       6.77 GB / 32.00 GB (21.2%)
Disk Space Avail:   3.26 GB / 926.35 GB (0.4%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run001_20260930_095418/quant"
Train Data Rows:    1377032
Train Data Columns: 14
Label Column:       Num_opps_minus_one
Problem Type:       quantile
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    7193.15 MB
	Train Data (Original)  Memory Usage: 73.54 MB (1.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 13 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 13 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.5s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 73.54 MB (1.0% of available memory)
Data preprocessing and feature engineering runtime = 1.65s ...
AutoGluon will gauge predictive performance using evaluation metric: 'pinball_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'XGB': [{}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 3 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 376.58s of the 565.02s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 1491. Best iteration is:
	[1467]	valid_set's quantile: 0.0234898
	Time limit exceeded... Skipping LightGBMXT_BAG_L1.
Fitting model: LightGBM_BAG_L1 ... Training model for up to 326.20s of the 514.63s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.0275	 = Validation score   (-pinball_loss)
	145.86s	 = Training   runtime
	16.72s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 162.55s of the 350.98s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 337. Best iteration is:
	[335]	valid_set's quantile: 0.0247435
	Ran out of time, early stopping on iteration 358. Best iteration is:
	[348]	valid_set's quantile: 0.0247431
	Ran out of time, early stopping on iteration 359. Best iteration is:
	[349]	valid_set's quantile: 0.0249138
	Ran out of time, early stopping on iteration 366. Best iteration is:
	[366]	valid_set's quantile: 0.0249366
	Ran out of time, early stopping on iteration 379. Best iteration is:
	[379]	valid_set's quantile: 0.0244524
	Ran out of time, early stopping on iteration 394. Best iteration is:
	[394]	valid_set's quantile: 0.024285
	Ran out of time, early stopping on iteration 411. Best iteration is:
	[411]	valid_set's quantile: 0.0247103
	Ran out of time, early stopping on iteration 459. Best iteration is:
	[453]	valid_set's quantile: 0.0240391
	-0.0246	 = Validation score   (-pinball_loss)
	139.77s	 = Training   runtime
	20.09s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 190.05s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/10.4 GB
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	-0.0246	 = Validation score   (-pinball_loss)
	0.69s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting 3 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 189.27s of the 189.24s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 909. Best iteration is:
	[887]	valid_set's quantile: 0.0236772
	Time limit exceeded... Skipping LightGBMXT_BAG_L2.
Fitting model: LightGBM_BAG_L2 ... Training model for up to 162.86s of the 162.84s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 680. Best iteration is:
	[679]	valid_set's quantile: 0.0273948
	Ran out of time, early stopping on iteration 774. Best iteration is:
	[596]	valid_set's quantile: 0.0280318
	-0.028	 = Validation score   (-pinball_loss)
	113.26s	 = Training   runtime
	15.32s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L2 ... Training model for up to 33.30s of the 33.27s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 68. Best iteration is:
	[68]	valid_set's quantile: 0.0417575
	Time limit exceeded... Skipping LightGBMLarge_BAG_L2.
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the 28.47s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/10.5 GB
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	-0.0246	 = Validation score   (-pinball_loss)
	1.09s	 = Training   runtime
	0.03s	 = Validation runtime
AutoGluon training complete, total runtime = 539.48s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 8566.7 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/10.4 GB
	12.92s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMLarge_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/10.4 GB
	17.51s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	0.69s	 = Training   runtime
Fitting 1 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L2_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/10.4 GB
	11.27s	 = Training   runtime
Fitting model: WeightedEnsemble_L3_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	1.09s	 = Training   runtime
Updated best model to "LightGBMLarge_BAG_L1_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "LightGBMLarge_BAG_L1_FULL" for predict() and predict_proba().
Refit complete, total runtime = 43.07s ... Best model: "LightGBMLarge_BAG_L1_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run001_20260930_095418/quant")
Using OOF from "LightGBMLarge_BAG_L1" as a proxy for "LightGBMLarge_BAG_L1_FULL".
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       10.43 GB / 32.00 GB (32.6%)
Disk Space Avail:   3.98 GB / 926.35 GB (0.4%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run001_20260930_095418/bin"
Train Data Rows:    1377032
Train Data Columns: 15
Label Column:       Is_Past_Threshold
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float32(1.0), np.float32(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10766.95 MB
	Train Data (Original)  Memory Usage: 84.05 MB (0.8% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 14 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 14 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.4s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 84.05 MB (0.8% of available memory)
Data preprocessing and feature engineering runtime = 1.46s ...
AutoGluon will gauge predictive performance using evaluation metric: 'log_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'XGB': [{}, {'learning_rate': 0.5, 'max_depth': 3, 'min_child_weight': 18, 'subsample': 1.0, 'ag_args': {'name_suffix': '_tuned'}}],
}
Fitting 4 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 565.21s of the 565.21s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)

[1000]	valid_set's binary_logloss: 0.147006
[2000]	valid_set's binary_logloss: 0.146756
[1000]	valid_set's binary_logloss: 0.148321
[2000]	valid_set's binary_logloss: 0.148081
[3000]	valid_set's binary_logloss: 0.148136

	-0.1484	 = Validation score   (-log_loss)
	112.93s	 = Training   runtime
	27.92s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 423.33s of the 423.33s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.147	 = Validation score   (-log_loss)
	371.03s	 = Training   runtime
	7.28s	 = Validation runtime
Fitting model: XGBoost_tuned_BAG_L1 ... Training model for up to 43.96s of the 43.96s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.1488	 = Validation score   (-log_loss)
	40.8s	 = Training   runtime
	0.76s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1.33s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/10.2 GB
	Ensemble Weights: {'XGBoost_BAG_L1': 0.833, 'LightGBM_BAG_L1': 0.167}
	-0.1469	 = Validation score   (-log_loss)
	1.03s	 = Training   runtime
	0.03s	 = Validation runtime
AutoGluon training complete, total runtime = 566.67s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4889.8 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.6/10.0 GB
	11.52s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0
	32.97s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_tuned_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0
	4.53s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'XGBoost_BAG_L1': 0.833, 'LightGBM_BAG_L1': 0.167}
	1.03s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 50.42s ... Best model: "WeightedEnsemble_L2_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run001_20260930_095418/bin")
Using OOF from "LightGBM_BAG_L1" as a proxy for "LightGBM_BAG_L1_FULL".
Using OOF from "LightGBMLarge_BAG_L1" as a proxy for "LightGBMLarge_BAG_L1_FULL".
Using OOF from "WeightedEnsemble_L2" as a proxy for "WeightedEnsemble_L2_FULL".

Positive examples from filter list: 43
Positive examples from multi-opp mislinkages: 96
Positive examples (high extension difficulty): 1732
Negative examples (low extension difficulty): 456936
Training set after refinement: 457935

/Users/petervw/GitHub/ActivitySCOPE/activityscope_utils.py:2050: RuntimeWarning: invalid value encountered in sqrt
  sqrt_1pe, sqrt_1me = col(np.sqrt(1.0 + e)), col(np.sqrt(1.0 - e))
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       10.34 GB / 32.00 GB (32.3%)
Disk Space Avail:   4.47 GB / 926.35 GB (0.5%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.

===== run 2 of 5 done in 36.2 min =====

===== run 3 of 5 (seed 1002), started 2026-09-30 10:30 =====

Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run002_20260930_103028/reg"
Train Data Rows:    1377032
Train Data Columns: 13
Label Column:       Num_opps_minus_one
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10599.11 MB
	Train Data (Original)  Memory Usage: 63.04 MB (0.6% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 12 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 12 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.3s = Fit runtime
	12 features in original data used to generate 12 features in processed data.
	Train Data (Processed) Memory Usage: 63.04 MB (0.6% of available memory)
Data preprocessing and feature engineering runtime = 1.33s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_poisson_deviance'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'objective': 'poisson', 'num_iterations': 1000, 'learning_rate': 0.1}],
	'XGB': [{'objective': 'count:poisson'}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 565.34s of the 565.34s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)

[1000]	valid_set's poisson: -13.1993	valid_set's mean_poisson_deviance: -0.386213
[1000]	valid_set's poisson: -13.2413	valid_set's mean_poisson_deviance: -0.384259
[1000]	valid_set's poisson: -13.2473	valid_set's mean_poisson_deviance: -0.38387
[1000]	valid_set's poisson: -13.2681	valid_set's mean_poisson_deviance: -0.382209
[1000]	valid_set's poisson: -13.2518	valid_set's mean_poisson_deviance: -0.383911
[1000]	valid_set's poisson: -13.2543	valid_set's mean_poisson_deviance: -0.38276
[1000]	valid_set's poisson: -13.2517	valid_set's mean_poisson_deviance: -0.383944
[1000]	valid_set's poisson: -13.2095	valid_set's mean_poisson_deviance: -0.387567

	-0.3843	 = Validation score   (-mean_poisson_deviance)
	169.48s	 = Training   runtime
	55.31s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 339.60s of the 339.60s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.3886	 = Validation score   (-mean_poisson_deviance)
	320.06s	 = Training   runtime
	6.74s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 11.80s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/9.1 GB
	Ensemble Weights: {'LightGBM_BAG_L1': 0.889, 'XGBoost_BAG_L1': 0.111}
	-0.3843	 = Validation score   (-mean_poisson_deviance)
	0.81s	 = Training   runtime
	0.02s	 = Validation runtime
AutoGluon training complete, total runtime = 555.87s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 2773.8 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.4/9.1 GB
	16.39s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0
	32.03s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBM_BAG_L1': 0.889, 'XGBoost_BAG_L1': 0.111}
	0.81s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 49.29s ... Best model: "WeightedEnsemble_L2_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run002_20260930_103028/reg")
Using OOF from "WeightedEnsemble_L2" as a proxy for "WeightedEnsemble_L2_FULL".
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       9.05 GB / 32.00 GB (28.3%)
Disk Space Avail:   5.06 GB / 926.35 GB (0.5%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run002_20260930_103028/quant"
Train Data Rows:    1377032
Train Data Columns: 14
Label Column:       Num_opps_minus_one
Problem Type:       quantile
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9396.99 MB
	Train Data (Original)  Memory Usage: 73.54 MB (0.8% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 13 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 13 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.4s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 73.54 MB (0.8% of available memory)
Data preprocessing and feature engineering runtime = 1.48s ...
AutoGluon will gauge predictive performance using evaluation metric: 'pinball_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'XGB': [{}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 3 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 376.69s of the 565.18s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 1811. Best iteration is:
	[1732]	valid_set's quantile: 0.0234248
	Time limit exceeded... Skipping LightGBMXT_BAG_L1.
Fitting model: LightGBM_BAG_L1 ... Training model for up to 324.74s of the 513.23s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.0275	 = Validation score   (-pinball_loss)
	136.31s	 = Training   runtime
	16.79s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 170.64s of the 359.12s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 381. Best iteration is:
	[381]	valid_set's quantile: 0.0243553
	Ran out of time, early stopping on iteration 388. Best iteration is:
	[388]	valid_set's quantile: 0.0242108
	Ran out of time, early stopping on iteration 374. Best iteration is:
	[369]	valid_set's quantile: 0.024871
	Ran out of time, early stopping on iteration 391. Best iteration is:
	[391]	valid_set's quantile: 0.0241507
	Ran out of time, early stopping on iteration 406. Best iteration is:
	[406]	valid_set's quantile: 0.0243501
	Ran out of time, early stopping on iteration 411. Best iteration is:
	[411]	valid_set's quantile: 0.0244831
	Ran out of time, early stopping on iteration 434. Best iteration is:
	[434]	valid_set's quantile: 0.0241746
	Ran out of time, early stopping on iteration 456. Best iteration is:
	[456]	valid_set's quantile: 0.0239652
	-0.0243	 = Validation score   (-pinball_loss)
	145.94s	 = Training   runtime
	22.09s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 190.03s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/9.2 GB
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	-0.0243	 = Validation score   (-pinball_loss)
	0.77s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting 3 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 189.18s of the 189.16s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 887. Best iteration is:
	[868]	valid_set's quantile: 0.0235621
	Time limit exceeded... Skipping LightGBMXT_BAG_L2.
Fitting model: LightGBM_BAG_L2 ... Training model for up to 162.95s of the 162.93s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 714. Best iteration is:
	[656]	valid_set's quantile: 0.0273579
	Ran out of time, early stopping on iteration 730. Best iteration is:
	[681]	valid_set's quantile: 0.0269663
	Ran out of time, early stopping on iteration 694. Best iteration is:
	[583]	valid_set's quantile: 0.0280397
	-0.028	 = Validation score   (-pinball_loss)
	130.39s	 = Training   runtime
	17.02s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L2 ... Training model for up to 14.50s of the 14.48s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 21. Best iteration is:
	[21]	valid_set's quantile: 0.0512417
	Time limit exceeded... Skipping LightGBMLarge_BAG_L2.
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the 11.87s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/8.8 GB
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	-0.0243	 = Validation score   (-pinball_loss)
	1.27s	 = Training   runtime
	0.03s	 = Validation runtime
AutoGluon training complete, total runtime = 556.26s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 7789.2 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/8.9 GB
	13.36s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMLarge_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/8.9 GB
	18.98s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	0.77s	 = Training   runtime
Fitting 1 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L2_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/9.0 GB
	13.6s	 = Training   runtime
Fitting model: WeightedEnsemble_L3_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	1.27s	 = Training   runtime
Updated best model to "LightGBMLarge_BAG_L1_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "LightGBMLarge_BAG_L1_FULL" for predict() and predict_proba().
Refit complete, total runtime = 47.39s ... Best model: "LightGBMLarge_BAG_L1_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run002_20260930_103028/quant")
Using OOF from "LightGBMLarge_BAG_L1" as a proxy for "LightGBMLarge_BAG_L1_FULL".
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       9.02 GB / 32.00 GB (28.2%)
Disk Space Avail:   4.92 GB / 926.35 GB (0.5%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run002_20260930_103028/bin"
Train Data Rows:    1377032
Train Data Columns: 15
Label Column:       Is_Past_Threshold
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float32(1.0), np.float32(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9308.91 MB
	Train Data (Original)  Memory Usage: 84.05 MB (0.9% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 14 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 14 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.5s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 84.05 MB (0.9% of available memory)
Data preprocessing and feature engineering runtime = 1.64s ...
AutoGluon will gauge predictive performance using evaluation metric: 'log_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'XGB': [{}, {'learning_rate': 0.5, 'max_depth': 3, 'min_child_weight': 18, 'subsample': 1.0, 'ag_args': {'name_suffix': '_tuned'}}],
}
Fitting 4 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 565.02s of the 565.02s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)

[1000]	valid_set's binary_logloss: 0.147963
[2000]	valid_set's binary_logloss: 0.14787

	-0.1483	 = Validation score   (-log_loss)
	62.83s	 = Training   runtime
	14.27s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 486.82s of the 486.82s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.1469	 = Validation score   (-log_loss)
	347.57s	 = Training   runtime
	6.24s	 = Validation runtime
Fitting model: XGBoost_tuned_BAG_L1 ... Training model for up to 131.85s of the 131.85s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.1475	 = Validation score   (-log_loss)
	123.8s	 = Training   runtime
	1.85s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 4.95s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/8.1 GB
	Ensemble Weights: {'XGBoost_BAG_L1': 0.688, 'XGBoost_tuned_BAG_L1': 0.25, 'LightGBM_BAG_L1': 0.062}
	-0.1468	 = Validation score   (-log_loss)
	1.2s	 = Training   runtime
	0.03s	 = Validation runtime
AutoGluon training complete, total runtime = 563.17s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 7697.5 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.6/8.0 GB
	6.71s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0
	28.55s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_tuned_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0
	10.92s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'XGBoost_BAG_L1': 0.688, 'XGBoost_tuned_BAG_L1': 0.25, 'LightGBM_BAG_L1': 0.062}
	1.2s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 47.54s ... Best model: "WeightedEnsemble_L2_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run002_20260930_103028/bin")
Using OOF from "WeightedEnsemble_L2" as a proxy for "WeightedEnsemble_L2_FULL".
Using OOF from "LightGBMLarge_BAG_L1" as a proxy for "LightGBMLarge_BAG_L1_FULL".
Using OOF from "WeightedEnsemble_L2" as a proxy for "WeightedEnsemble_L2_FULL".

Positive examples from filter list: 43
Positive examples from multi-opp mislinkages: 96
Positive examples (high extension difficulty): 1761
Negative examples (low extension difficulty): 456794
Training set after refinement: 457790

/Users/petervw/GitHub/ActivitySCOPE/activityscope_utils.py:2050: RuntimeWarning: invalid value encountered in sqrt
  sqrt_1pe, sqrt_1me = col(np.sqrt(1.0 + e)), col(np.sqrt(1.0 - e))
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       10.57 GB / 32.00 GB (33.0%)
Disk Space Avail:   4.59 GB / 926.35 GB (0.5%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.

===== run 3 of 5 done in 35.0 min =====

===== run 4 of 5 (seed 1003), started 2026-09-30 11:05 =====

Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run003_20260930_110526/reg"
Train Data Rows:    1377032
Train Data Columns: 13
Label Column:       Num_opps_minus_one
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10882.55 MB
	Train Data (Original)  Memory Usage: 63.04 MB (0.6% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 12 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 12 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.2s = Fit runtime
	12 features in original data used to generate 12 features in processed data.
	Train Data (Processed) Memory Usage: 63.04 MB (0.6% of available memory)
Data preprocessing and feature engineering runtime = 1.26s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_poisson_deviance'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'objective': 'poisson', 'num_iterations': 1000, 'learning_rate': 0.1}],
	'XGB': [{'objective': 'count:poisson'}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 565.41s of the 565.41s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)

[1000]	valid_set's poisson: -13.2895	valid_set's mean_poisson_deviance: -0.38422
[1000]	valid_set's poisson: -13.2015	valid_set's mean_poisson_deviance: -0.384884
[1000]	valid_set's poisson: -13.2291	valid_set's mean_poisson_deviance: -0.386188
[1000]	valid_set's poisson: -13.2168	valid_set's mean_poisson_deviance: -0.386694
[1000]	valid_set's poisson: -13.238	valid_set's mean_poisson_deviance: -0.384536
[1000]	valid_set's poisson: -13.2118	valid_set's mean_poisson_deviance: -0.384752
[1000]	valid_set's poisson: -13.2637	valid_set's mean_poisson_deviance: -0.384005
[1000]	valid_set's poisson: -13.272	valid_set's mean_poisson_deviance: -0.381392

	-0.3846	 = Validation score   (-mean_poisson_deviance)
	158.93s	 = Training   runtime
	54.02s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 351.59s of the 351.59s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.3878	 = Validation score   (-mean_poisson_deviance)
	331.4s	 = Training   runtime
	6.91s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 12.38s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/10.2 GB
	Ensemble Weights: {'LightGBM_BAG_L1': 0.8, 'XGBoost_BAG_L1': 0.2}
	-0.3844	 = Validation score   (-mean_poisson_deviance)
	0.68s	 = Training   runtime
	0.01s	 = Validation runtime
AutoGluon training complete, total runtime = 555.1s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 2824.8 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.4/10.2 GB
	14.84s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0
	33.83s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBM_BAG_L1': 0.8, 'XGBoost_BAG_L1': 0.2}
	0.68s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 49.51s ... Best model: "WeightedEnsemble_L2_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run003_20260930_110526/reg")
Using OOF from "WeightedEnsemble_L2" as a proxy for "WeightedEnsemble_L2_FULL".
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       10.19 GB / 32.00 GB (31.9%)
Disk Space Avail:   4.35 GB / 926.35 GB (0.5%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run003_20260930_110526/quant"
Train Data Rows:    1377032
Train Data Columns: 14
Label Column:       Num_opps_minus_one
Problem Type:       quantile
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10569.53 MB
	Train Data (Original)  Memory Usage: 73.54 MB (0.7% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 13 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 13 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.3s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 73.54 MB (0.7% of available memory)
Data preprocessing and feature engineering runtime = 1.37s ...
AutoGluon will gauge predictive performance using evaluation metric: 'pinball_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'XGB': [{}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 3 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 376.77s of the 565.30s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 1954. Best iteration is:
	[1933]	valid_set's quantile: 0.0235191
	Time limit exceeded... Skipping LightGBMXT_BAG_L1.
Fitting model: LightGBM_BAG_L1 ... Training model for up to 323.92s of the 512.45s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.0281	 = Validation score   (-pinball_loss)
	122.47s	 = Training   runtime
	15.57s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 184.89s of the 373.42s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 423. Best iteration is:
	[423]	valid_set's quantile: 0.0241028
	Ran out of time, early stopping on iteration 374. Best iteration is:
	[327]	valid_set's quantile: 0.0246728
	Ran out of time, early stopping on iteration 419. Best iteration is:
	[419]	valid_set's quantile: 0.0243092
	Ran out of time, early stopping on iteration 447. Best iteration is:
	[447]	valid_set's quantile: 0.0239793
	Ran out of time, early stopping on iteration 443. Best iteration is:
	[443]	valid_set's quantile: 0.0242567
	Ran out of time, early stopping on iteration 444. Best iteration is:
	[442]	valid_set's quantile: 0.025038
	Ran out of time, early stopping on iteration 482. Best iteration is:
	[419]	valid_set's quantile: 0.0242231
	Ran out of time, early stopping on iteration 512. Best iteration is:
	[512]	valid_set's quantile: 0.0239495
	-0.0243	 = Validation score   (-pinball_loss)
	159.42s	 = Training   runtime
	22.86s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 190.15s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/9.9 GB
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	-0.0243	 = Validation score   (-pinball_loss)
	0.81s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting 3 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 189.26s of the 189.24s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 898. Best iteration is:
	[892]	valid_set's quantile: 0.0236167
	Time limit exceeded... Skipping LightGBMXT_BAG_L2.
Fitting model: LightGBM_BAG_L2 ... Training model for up to 162.89s of the 162.87s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 652. Best iteration is:
	[530]	valid_set's quantile: 0.027756
	Ran out of time, early stopping on iteration 730. Best iteration is:
	[688]	valid_set's quantile: 0.0277892
	Ran out of time, early stopping on iteration 764. Best iteration is:
	[763]	valid_set's quantile: 0.0268797
	Ran out of time, early stopping on iteration 862. Best iteration is:
	[661]	valid_set's quantile: 0.0279203
	Ran out of time, early stopping on iteration 817. Best iteration is:
	[626]	valid_set's quantile: 0.0266711
	-0.0273	 = Validation score   (-pinball_loss)
	140.36s	 = Training   runtime
	18.93s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the 2.26s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/9.5 GB
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	-0.0243	 = Validation score   (-pinball_loss)
	1.27s	 = Training   runtime
	0.03s	 = Validation runtime
AutoGluon training complete, total runtime = 565.86s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 7528.3 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/9.5 GB
	12.4s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMLarge_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/9.5 GB
	19.65s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	0.81s	 = Training   runtime
Fitting 1 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L2_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/9.4 GB
	14.39s	 = Training   runtime
Fitting model: WeightedEnsemble_L3_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMLarge_BAG_L1': 1.0}
	1.27s	 = Training   runtime
Updated best model to "LightGBMLarge_BAG_L1_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "LightGBMLarge_BAG_L1_FULL" for predict() and predict_proba().
Refit complete, total runtime = 47.9s ... Best model: "LightGBMLarge_BAG_L1_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run003_20260930_110526/quant")
Using OOF from "LightGBMLarge_BAG_L1" as a proxy for "LightGBMLarge_BAG_L1_FULL".
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       9.39 GB / 32.00 GB (29.4%)
Disk Space Avail:   4.09 GB / 926.35 GB (0.4%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run003_20260930_110526/bin"
Train Data Rows:    1377032
Train Data Columns: 15
Label Column:       Is_Past_Threshold
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float32(1.0), np.float32(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9726.67 MB
	Train Data (Original)  Memory Usage: 84.05 MB (0.9% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 14 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 14 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.4s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 84.05 MB (0.9% of available memory)
Data preprocessing and feature engineering runtime = 1.56s ...
AutoGluon will gauge predictive performance using evaluation metric: 'log_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'XGB': [{}, {'learning_rate': 0.5, 'max_depth': 3, 'min_child_weight': 18, 'subsample': 1.0, 'ag_args': {'name_suffix': '_tuned'}}],
}
Fitting 4 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 565.11s of the 565.11s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)

[1000]	valid_set's binary_logloss: 0.149207
[2000]	valid_set's binary_logloss: 0.148947
[3000]	valid_set's binary_logloss: 0.148956
[1000]	valid_set's binary_logloss: 0.14603
[2000]	valid_set's binary_logloss: 0.146003
[1000]	valid_set's binary_logloss: 0.146446
[2000]	valid_set's binary_logloss: 0.146252

	-0.148	 = Validation score   (-log_loss)
	151.5s	 = Training   runtime
	39.14s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 372.50s of the 372.50s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.147	 = Validation score   (-log_loss)
	321.98s	 = Training   runtime
	6.36s	 = Validation runtime
Fitting model: XGBoost_tuned_BAG_L1 ... Training model for up to 42.98s of the 42.98s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.1487	 = Validation score   (-log_loss)
	39.85s	 = Training   runtime
	0.75s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1.10s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/8.5 GB
	Ensemble Weights: {'XGBoost_BAG_L1': 0.8, 'LightGBM_BAG_L1': 0.2}
	-0.1469	 = Validation score   (-log_loss)
	1.06s	 = Training   runtime
	0.02s	 = Validation runtime
AutoGluon training complete, total runtime = 567.0s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 3783.2 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.6/8.5 GB
	15.62s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0
	29.1s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_tuned_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0
	4.44s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'XGBoost_BAG_L1': 0.8, 'LightGBM_BAG_L1': 0.2}
	1.06s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 51.02s ... Best model: "WeightedEnsemble_L2_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run003_20260930_110526/bin")
Using OOF from "WeightedEnsemble_L2" as a proxy for "WeightedEnsemble_L2_FULL".
Using OOF from "LightGBMLarge_BAG_L1" as a proxy for "LightGBMLarge_BAG_L1_FULL".
Using OOF from "WeightedEnsemble_L2" as a proxy for "WeightedEnsemble_L2_FULL".

Positive examples from filter list: 43
Positive examples from multi-opp mislinkages: 96
Positive examples (high extension difficulty): 1743
Negative examples (low extension difficulty): 456844
Training set after refinement: 457804

/Users/petervw/GitHub/ActivitySCOPE/activityscope_utils.py:2050: RuntimeWarning: invalid value encountered in sqrt
  sqrt_1pe, sqrt_1me = col(np.sqrt(1.0 + e)), col(np.sqrt(1.0 - e))
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       10.09 GB / 32.00 GB (31.5%)
Disk Space Avail:   4.89 GB / 926.35 GB (0.5%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.

===== run 4 of 5 done in 35.7 min =====

===== run 5 of 5 (seed 1004), started 2026-09-30 11:41 =====

Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run004_20260930_114106/reg"
Train Data Rows:    1377032
Train Data Columns: 13
Label Column:       Num_opps_minus_one
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10295.30 MB
	Train Data (Original)  Memory Usage: 63.04 MB (0.6% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 12 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 12 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.3s = Fit runtime
	12 features in original data used to generate 12 features in processed data.
	Train Data (Processed) Memory Usage: 63.04 MB (0.6% of available memory)
Data preprocessing and feature engineering runtime = 1.33s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_poisson_deviance'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'objective': 'poisson', 'num_iterations': 1000, 'learning_rate': 0.1}],
	'XGB': [{'objective': 'count:poisson'}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 565.34s of the 565.34s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)

[1000]	valid_set's poisson: -13.1796	valid_set's mean_poisson_deviance: -0.386428
[1000]	valid_set's poisson: -13.2284	valid_set's mean_poisson_deviance: -0.38417
[1000]	valid_set's poisson: -13.2215	valid_set's mean_poisson_deviance: -0.386535
[1000]	valid_set's poisson: -13.2485	valid_set's mean_poisson_deviance: -0.381764
[1000]	valid_set's poisson: -13.2831	valid_set's mean_poisson_deviance: -0.384656
[1000]	valid_set's poisson: -13.2788	valid_set's mean_poisson_deviance: -0.379019
[1000]	valid_set's poisson: -13.2379	valid_set's mean_poisson_deviance: -0.386
[1000]	valid_set's poisson: -13.2451	valid_set's mean_poisson_deviance: -0.386802

	-0.3844	 = Validation score   (-mean_poisson_deviance)
	164.91s	 = Training   runtime
	55.0s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 344.53s of the 344.53s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.3883	 = Validation score   (-mean_poisson_deviance)
	324.73s	 = Training   runtime
	6.76s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 11.92s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/6.1 GB
	Ensemble Weights: {'LightGBM_BAG_L1': 0.857, 'XGBoost_BAG_L1': 0.143}
	-0.3843	 = Validation score   (-mean_poisson_deviance)
	0.79s	 = Training   runtime
	0.02s	 = Validation runtime
AutoGluon training complete, total runtime = 555.71s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 2787.0 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.4/6.6 GB
	16.35s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0
	33.38s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBM_BAG_L1': 0.857, 'XGBoost_BAG_L1': 0.143}
	0.79s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 50.67s ... Best model: "WeightedEnsemble_L2_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run004_20260930_114106/reg")
Using OOF from "WeightedEnsemble_L2" as a proxy for "WeightedEnsemble_L2_FULL".
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       6.36 GB / 32.00 GB (19.9%)
Disk Space Avail:   4.57 GB / 926.35 GB (0.5%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run004_20260930_114106/quant"
Train Data Rows:    1377032
Train Data Columns: 14
Label Column:       Num_opps_minus_one
Problem Type:       quantile
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6784.39 MB
	Train Data (Original)  Memory Usage: 73.54 MB (1.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 13 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 13 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.6s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 73.54 MB (1.1% of available memory)
Data preprocessing and feature engineering runtime = 1.82s ...
AutoGluon will gauge predictive performance using evaluation metric: 'pinball_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'XGB': [{}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 3 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 376.47s of the 564.85s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 1398. Best iteration is:
	[1397]	valid_set's quantile: 0.0236254
	Time limit exceeded... Skipping LightGBMXT_BAG_L1.
Fitting model: LightGBM_BAG_L1 ... Training model for up to 326.60s of the 514.97s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.0275	 = Validation score   (-pinball_loss)
	185.38s	 = Training   runtime
	17.63s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 121.97s of the 310.35s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 198. Best iteration is:
	[198]	valid_set's quantile: 0.0284264
	Ran out of time, early stopping on iteration 109. Best iteration is:
	[109]	valid_set's quantile: 0.0359568
	Ran out of time, early stopping on iteration 182. Best iteration is:
	[182]	valid_set's quantile: 0.0291349
	Ran out of time, early stopping on iteration 182. Best iteration is:
	[182]	valid_set's quantile: 0.0290133
	Ran out of time, early stopping on iteration 147. Best iteration is:
	[147]	valid_set's quantile: 0.0304349
	Ran out of time, early stopping on iteration 219. Best iteration is:
	[219]	valid_set's quantile: 0.0271835
	Ran out of time, early stopping on iteration 193. Best iteration is:
	[193]	valid_set's quantile: 0.0287545
	Ran out of time, early stopping on iteration 282. Best iteration is:
	[282]	valid_set's quantile: 0.0259598
	-0.0294	 = Validation score   (-pinball_loss)
	108.12s	 = Training   runtime
	10.84s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 189.59s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/5.9 GB
	Ensemble Weights: {'LightGBM_BAG_L1': 1.0}
	-0.0275	 = Validation score   (-pinball_loss)
	0.89s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting 3 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 188.42s of the 188.39s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 560. Best iteration is:
	[559]	valid_set's quantile: 0.0237204
	Time limit exceeded... Skipping LightGBMXT_BAG_L2.
Fitting model: LightGBM_BAG_L2 ... Training model for up to 163.60s of the 163.57s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 501. Best iteration is:
	[501]	valid_set's quantile: 0.028293
	Ran out of time, early stopping on iteration 556. Best iteration is:
	[556]	valid_set's quantile: 0.0322809
	Ran out of time, early stopping on iteration 576. Best iteration is:
	[575]	valid_set's quantile: 0.0270351
	Ran out of time, early stopping on iteration 685. Best iteration is:
	[662]	valid_set's quantile: 0.027349
	Ran out of time, early stopping on iteration 753. Best iteration is:
	[708]	valid_set's quantile: 0.027881
	Ran out of time, early stopping on iteration 597. Best iteration is:
	[595]	valid_set's quantile: 0.0270177
	Ran out of time, early stopping on iteration 661. Best iteration is:
	[552]	valid_set's quantile: 0.0273629
	-0.0281	 = Validation score   (-pinball_loss)
	141.28s	 = Training   runtime
	18.1s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the 2.18s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/6.2 GB
	Ensemble Weights: {'LightGBM_BAG_L1': 1.0}
	-0.0275	 = Validation score   (-pinball_loss)
	1.3s	 = Training   runtime
	0.04s	 = Validation runtime
AutoGluon training complete, total runtime = 566.31s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 9759.2 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/6.1 GB
	20.38s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMLarge_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/6.4 GB
	16.94s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBM_BAG_L1': 1.0}
	0.89s	 = Training   runtime
Fitting 1 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L2_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.5/6.2 GB
	21.57s	 = Training   runtime
Fitting model: WeightedEnsemble_L3_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBM_BAG_L1': 1.0}
	1.3s	 = Training   runtime
Updated best model to "LightGBM_BAG_L1_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "LightGBM_BAG_L1_FULL" for predict() and predict_proba().
Refit complete, total runtime = 63.81s ... Best model: "LightGBM_BAG_L1_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run004_20260930_114106/quant")
Using OOF from "LightGBM_BAG_L1" as a proxy for "LightGBM_BAG_L1_FULL".
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.11.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.6.0: Tue Jul 21 20:51:05 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       6.48 GB / 32.00 GB (20.2%)
Disk Space Avail:   2.29 GB / 926.35 GB (0.2%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['good_quality']
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
Values in column 'Shared_Fold' used as split folds instead of being automatically set. Bagged models will have 8 splits.
Beginning AutoGluon training ... Time limit = 567s
AutoGluon will save models to "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run004_20260930_114106/bin"
Train Data Rows:    1377032
Train Data Columns: 15
Label Column:       Is_Past_Threshold
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float32(1.0), np.float32(0.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6718.38 MB
	Train Data (Original)  Memory Usage: 84.05 MB (1.3% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 14 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 14 | ['H', 'Node', 'a', 'i', 'vis_q', ...]
	1.5s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 84.05 MB (1.3% of available memory)
Data preprocessing and feature engineering runtime = 1.63s ...
AutoGluon will gauge predictive performance using evaluation metric: 'log_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'XGB': [{}, {'learning_rate': 0.5, 'max_depth': 3, 'min_child_weight': 18, 'subsample': 1.0, 'ag_args': {'name_suffix': '_tuned'}}],
}
Fitting 4 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1 ... Training model for up to 565.04s of the 565.04s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)

[1000]	valid_set's binary_logloss: 0.147017
[2000]	valid_set's binary_logloss: 0.146907
[1000]	valid_set's binary_logloss: 0.14706
[2000]	valid_set's binary_logloss: 0.146784

	Ran out of time, early stopping on iteration 2108. Best iteration is:
	[2107]	valid_set's binary_logloss: 0.146767

[1000]	valid_set's binary_logloss: 0.146828
[2000]	valid_set's binary_logloss: 0.146752

	Ran out of time, early stopping on iteration 2382. Best iteration is:
	[1936]	valid_set's binary_logloss: 0.146735

[1000]	valid_set's binary_logloss: 0.148346
[2000]	valid_set's binary_logloss: 0.148111

	-0.1478	 = Validation score   (-log_loss)
	347.63s	 = Training   runtime
	49.51s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 166.45s of the 166.45s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.1474	 = Validation score   (-log_loss)
	155.91s	 = Training   runtime
	3.59s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 4.91s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.1/5.8 GB
	Ensemble Weights: {'XGBoost_BAG_L1': 0.667, 'LightGBM_BAG_L1': 0.333}
	-0.1473	 = Validation score   (-log_loss)
	1.2s	 = Training   runtime
	0.03s	 = Validation runtime
AutoGluon training complete, total runtime = 564.91s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 3241.3 rows/s (172129 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.6/5.7 GB
	32.3s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0
	16.33s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'XGBoost_BAG_L1': 0.667, 'LightGBM_BAG_L1': 0.333}
	1.2s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 52.55s ... Best model: "WeightedEnsemble_L2_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/activityscope_ag_multi/table3_seed_sweep_run004_20260930_114106/bin")
Using OOF from "WeightedEnsemble_L2" as a proxy for "WeightedEnsemble_L2_FULL".
Using OOF from "LightGBM_BAG_L1" as a proxy for "LightGBM_BAG_L1_FULL".
Using OOF from "WeightedEnsemble_L2" as a proxy for "WeightedEnsemble_L2_FULL".

Positive examples from filter list: 43
Positive examples from multi-opp mislinkages: 96
Positive examples (high extension difficulty): 1744
Negative examples (low extension difficulty): 456617
Training set after refinement: 457619

/Users/petervw/GitHub/ActivitySCOPE/activityscope_utils.py:2050: RuntimeWarning: invalid value encountered in sqrt
  sqrt_1pe, sqrt_1me = col(np.sqrt(1.0 + e)), col(np.sqrt(1.0 - e))

  parquet failed for run_004_final (OSError: [Errno 28] Error writing bytes to file. Detail: [errno 28] No space left on device); saving as pickle
Traceback (most recent call last):
  File "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/ipykernel_15618/4115635105.py", line 28, in <module>
    run_once(run_idx)
  File "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/ipykernel_15618/915795175.py", line 100, in run_once
    paths = {"final": save_frame(final, stem + "_final"),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/ipykernel_15618/2559230349.py", line 76, in save_frame
    df.to_pickle(path)
  File "/Users/petervw/mambaforge/envs/actscope-16/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petervw/mambaforge/envs/actscope-16/lib/python3.11/site-packages/pandas/core/generic.py", line 3187, in to_pickle
    to_pickle(
  File "/Users/petervw/mambaforge/envs/actscope-16/lib/python3.11/site-packages/pandas/io/pickle.py", line 103, in to_pickle
    with get_handle(
         ^^^^^^^^^^^
  File "/Users/petervw/mambaforge/envs/actscope-16/lib/python3.11/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] No space left on device: 'multi_run_outputs/table3_seed_sweep/run_004_final.pkl'


sweep finished in 3.00 h

## Aggregate the runs
Everything below reads only the saved `run_XXX_table_rows.csv` files, so it can be re-run at any time (including while a sweep is still going, or after restarting the kernel once the parameter and data-loading cells above have run).

In [11]:
run_files = sorted(glob.glob(os.path.join(OUTPUT_DIR, "run_*_table_rows.csv")))
if not run_files:
    raise RuntimeError(f"No completed runs in {OUTPUT_DIR}")
all_runs = pd.concat([pd.read_csv(f) for f in run_files], ignore_index=True)
n_runs_done = all_runs["run"].nunique()
print(f"{n_runs_done} completed runs: {sorted(all_runs['run'].unique().tolist())}")

table_order = [r["designation"] for r in table_notes]
stats = (all_runs.groupby("designation")[TABLE_VALUE_COLS]
         .agg(["mean", "std", "median", "min", "max", "count"])
         .reindex(table_order))
stats.to_csv(os.path.join(OUTPUT_DIR, "table3_run_statistics.csv"))

summary = pd.DataFrame(index=table_order)
for c in TABLE_VALUE_COLS:
    summary[c] = stats[(c, "mean")]
    if c in PM_COLUMNS:
        summary[c + " ±"] = stats[(c, "std")]
display(summary)

not_found = all_runs.loc[~all_runs["found"].astype(bool)]
if len(not_found):
    print("Objects missing in some runs:")
    display(not_found.groupby("designation")["run"].apply(list))

3 completed runs: [1, 2, 3]

,q,a,e,i,TJ,H,Num_opps,exp_Num_opps,prob,prob ±,DeltaQ,DeltaQ ±,S_EV,S_EV ±,DeltaH,DeltaH ±
2010 RH69,4.276048,4.532396,0.056559,11.54822,2.973910,13.95,3.0,18.362625,0.999998,2.046194e-06,11.367557,0.560582,4.872054e-06,1.139392e-07,2.450000,0.000000
362P/(457175) 2008 GO98,2.864301,3.971173,0.278727,15.55983,2.926730,12.91,7.0,23.955757,0.999998,2.121001e-06,10.326086,0.272304,2.899841e-05,1.032173e-06,3.250000,0.000000
282P/(323137) 2003 BM80,3.438718,4.234372,0.187904,5.81319,2.991756,13.62,7.0,22.028741,0.999998,2.046835e-06,10.316230,0.262152,1.211888e-04,6.985267e-06,2.100000,0.000000
2017 QN84,2.474881,3.769087,0.343374,12.07147,2.943831,14.97,4.0,12.836535,0.999998,7.932139e-07,5.078355,0.053134,2.606914e-03,2.484737e-04,2.033333,0.028868
2008 VK110,4.436583,7.167172,0.380986,7.38588,2.878252,13.75,3.0,7.542647,0.987351,6.581392e-03,-0.151789,0.014297,4.258534e-02,1.138876e-02,1.333333,0.510718
2001 BV70,2.063079,3.593632,0.425907,4.33032,2.947403,15.14,1.0,15.953092,0.999999,4.520722e-07,10.967493,0.040507,3.224969e-07,4.305986e-08,4.416667,0.152753
P/2025 UX109 (Ye),2.569961,3.806430,0.324837,3.18090,2.982290,15.00,1.0,16.715579,0.999999,3.884326e-07,11.924029,0.047092,1.503797e-07,1.957071e-08,4.550000,0.050000
2019 OE31,3.942522,4.381322,0.100152,5.22115,3.006031,14.64,1.0,16.764423,0.999998,2.594039e-06,11.893297,0.058024,1.424757e-07,4.471353e-09,3.583333,0.251661
2018 BJ11,3.252873,4.200594,0.225616,3.43068,2.986205,15.55,1.0,10.351398,0.999991,1.238513e-05,5.006042,0.009696,8.690481e-05,4.019807e-06,3.300000,0.180278
P/2022 BV9 (Lemmon),3.347685,4.366555,0.233335,11.92230,2.934749,13.79,1.0,18.580412,0.999991,7.536389e-06,14.014337,0.000353,2.323031e-08,2.017759e-09,4.250000,0.346410
489P/Denning,1.561006,4.421537,0.646954,4.02690,2.579142,15.35,1.0,8.512345,0.999756,1.514734e-04,3.082958,0.102002,5.628439e-04,1.643822e-04,3.850000,0.086603
2024 XE22,4.535879,5.865080,0.226630,27.16003,2.727256,14.26,1.0,6.303197,0.989881,4.224246e-03,1.518805,0.352830,5.021306e-03,8.079003e-04,3.616667,0.585947
2009 DP2,3.822559,6.646579,0.424883,26.76899,2.609808,14.17,1.0,5.377837,0.951474,1.570915e-02,0.820981,0.435785,1.256363e-02,6.424361e-04,4.250000,0.173205
P/2023 JN16 (Lemmon),2.300095,2.697442,0.147305,3.70130,3.350239,15.73,1.0,19.689926,1.000000,4.466049e-07,15.014401,0.000065,7.646364e-09,3.984996e-10,4.483333,0.175594
2025 HV38,2.366069,2.484172,0.047542,7.24007,3.463847,15.42,1.0,21.093904,1.000000,1.704010e-07,16.113070,0.108429,1.878059e-09,9.569957e-11,5.166667,0.057735
2015 BC566,2.951045,3.063210,0.036617,11.68986,3.200295,16.33,1.0,13.652472,1.000000,1.214654e-07,9.005206,0.002382,3.201364e-06,1.290347e-07,2.966667,0.152753
2007 VB146,2.439879,2.752892,0.113703,3.49271,3.332674,16.94,1.0,14.815995,0.999999,2.458357e-07,9.994027,0.013812,9.995745e-07,1.322646e-08,2.600000,0.086603
2025 VZ8,2.394910,2.620616,0.086127,12.10031,3.368118,16.76,1.0,12.597596,0.999999,7.235275e-07,7.208795,0.116150,9.190318e-06,2.442653e-07,3.150000,0.173205
2008 BJ22,2.942906,3.073201,0.042397,11.51245,3.197832,15.20,1.0,20.564187,0.999999,4.803497e-07,16.014377,0.000315,3.192627e-09,2.303448e-10,4.300000,0.000000
2021 AY8,2.567449,2.722797,0.057054,5.00731,3.349841,17.52,1.0,12.343930,0.999998,6.769771e-07,6.980863,0.039246,1.185256e-05,6.425259e-07,3.050000,0.132288
2009 FP8,2.477724,3.014208,0.177985,4.62744,3.219233,16.94,1.0,11.788925,0.999997,1.266773e-06,6.300940,0.461654,2.063891e-05,8.745377e-07,3.750000,0.132288
P/2017 FL36 (PANSTARRS),2.828733,2.927577,0.033763,15.69930,3.220676,16.65,1.0,9.541052,0.999980,1.161179e-05,4.107223,0.045016,1.958222e-04,1.800177e-05,2.766667,0.028868
2010 TR241,2.746025,3.050750,0.099885,12.41983,3.193626,16.97,1.0,10.591459,0.999993,8.913722e-06,5.310132,0.520522,6.848411e-05,5.997363e-06,2.016667,0.057735
2002 CW116,2.068204,2.690282,0.231232,8.13852,3.319074,17.52,1.0,9.165663,0.999899,2.866724e-05,3.776472,0.243793,2.843401e-04,8.836707e-06,2.966667,0.076376

In [12]:
# Per-run values for each ± column, to see where the scatter comes from
for c in PM_COLUMNS:
    print(c)
    display(all_runs.pivot(index="designation", columns="run", values=c).reindex(table_order))

prob

run                             1         2         3
designation
2010 RH69                0.999999  0.999996  0.999999
362P/(457175) 2008 GO98  0.999999  0.999995  0.999999
282P/(323137) 2003 BM80  1.000000  0.999996  0.999999
2017 QN84                0.999999  0.999997  0.999999
2008 VK110               0.993622  0.987934  0.980498
2001 BV70                1.000000  0.999999  0.999999
P/2025 UX109 (Ye)        0.999999  0.999998  0.999999
2019 OE31                0.999999  0.999995  0.999999
2018 BJ11                0.999998  0.999976  0.999997
P/2022 BV9 (Lemmon)      0.999995  0.999983  0.999997
489P/Denning             0.999582  0.999857  0.999830
2024 XE22                0.990399  0.993823  0.985422
2009 DP2                 0.962325  0.933460  0.958636
P/2023 JN16 (Lemmon)     1.000000  0.999999  1.000000
2025 HV38                1.000000  0.999999  1.000000
2015 BC566               1.000000  1.000000  1.000000
2007 VB146               0.999999  0.999999  0.999999
2025 VZ8                 0.999999  0.999998  0.999999
2008 BJ22                1.000000  0.999999  0.999999
2021 AY8                 0.999999  0.999997  0.999998
2009 FP8                 0.999998  0.999996  0.999997
P/2017 FL36 (PANSTARRS)  0.999990  0.999983  0.999967
2010 TR241               0.999999  0.999983  0.999997
2002 CW116               0.999932  0.999880  0.999884

DeltaQ

run                              1          2          3
designation
2010 RH69                11.014337  12.013932  11.074403
362P/(457175) 2008 GO98  10.444122  10.014679  10.519457
282P/(323137) 2003 BM80  10.444122  10.014679  10.489889
2017 QN84                 5.043227   5.139482   5.052355
2008 VK110               -0.163414  -0.156129  -0.135825
2001 BV70                10.968197  11.007644  10.926639
P/2025 UX109 (Ye)        11.871028  11.940002  11.961057
2019 OE31                11.828341  11.940002  11.911547
2018 BJ11                 5.017069   5.002208   4.998849
P/2022 BV9 (Lemmon)      14.014501  14.013932  14.014579
489P/Denning              3.135844   3.147656   2.965375
2024 XE22                 1.405313   1.914414   1.236687
2009 DP2                  1.140009   0.324460   0.998475
P/2023 JN16 (Lemmon)     15.014326  15.014431  15.014446
2025 HV38                16.229319  16.014679  16.095211
2015 BC566                9.005733   9.002605   9.007280
2007 VB146               10.003626  10.000257   9.978197
2025 VZ8                  7.074751   7.279681   7.271952
2008 BJ22                16.014050  16.014679  16.014402
2021 AY8                  7.003960   6.935548   7.003082
2009 FP8                  6.040607   6.833963   6.028248
P/2017 FL36 (PANSTARRS)   4.152324   4.062293   4.107052
2010 TR241                5.017069   5.002208   5.911118
2002 CW116                3.496484   3.891171   3.941763

S_EV

run                                 1             2             3
designation
2010 RH69                4.982246e-06  4.754705e-06  4.879211e-06
362P/(457175) 2008 GO98  2.957216e-05  2.780684e-05  2.961625e-05
282P/(323137) 2003 BM80  1.150802e-04  1.196815e-04  1.288046e-04
2017 QN84                2.489060e-03  2.439297e-03  2.892384e-03
2008 VK110               3.451144e-02  3.763269e-02  5.561190e-02
2001 BV70                3.183791e-07  3.674677e-07  2.816438e-07
P/2025 UX109 (Ye)        1.347746e-07  1.440270e-07  1.723376e-07
2019 OE31                1.380852e-07  1.470237e-07  1.423180e-07
2018 BJ11                9.154470e-05  8.447354e-05  8.469618e-05
P/2022 BV9 (Lemmon)      2.415781e-08  2.091558e-08  2.461756e-08
489P/Denning             3.974018e-04  7.261454e-04  5.649846e-04
2024 XE22                5.680198e-03  4.119934e-03  5.263785e-03
2009 DP2                 1.183089e-02  1.282980e-02  1.303020e-02
P/2023 JN16 (Lemmon)     7.473498e-09  8.102107e-09  7.363487e-09
2025 HV38                1.772341e-09  1.903059e-09  1.958778e-09
2015 BC566               3.083217e-06  3.181820e-06  3.339057e-06
2007 VB146               1.000083e-06  1.012539e-06  9.861012e-07
2025 VZ8                 9.423205e-06  8.936077e-06  9.211670e-06
2008 BJ22                2.941427e-09  3.242514e-09  3.393941e-09
2021 AY8                 1.137615e-05  1.159819e-05  1.258332e-05
2009 FP8                 1.992322e-05  2.037978e-05  2.161373e-05
P/2017 FL36 (PANSTARRS)  1.895057e-04  1.818300e-04  2.161310e-04
2010 TR241               6.804465e-05  7.468911e-05  6.271856e-05
2002 CW116               2.859511e-04  2.922605e-04  2.748087e-04

DeltaH

run                         1     2     3
designation
2010 RH69                2.45  2.45  2.45
362P/(457175) 2008 GO98  3.25  3.25  3.25
282P/(323137) 2003 BM80  2.10  2.10  2.10
2017 QN84                2.00  2.05  2.05
2008 VK110               1.55  1.70  0.75
2001 BV70                4.55  4.45  4.25
P/2025 UX109 (Ye)        4.50  4.55  4.60
2019 OE31                3.35  3.85  3.55
2018 BJ11                3.50  3.15  3.25
P/2022 BV9 (Lemmon)      4.05  4.05  4.65
489P/Denning             3.80  3.80  3.95
2024 XE22                4.05  2.95  3.85
2009 DP2                 4.15  4.45  4.15
P/2023 JN16 (Lemmon)     4.65  4.30  4.50
2025 HV38                5.20  5.10  5.20
2015 BC566               3.00  3.10  2.80
2007 VB146               2.55  2.55  2.70
2025 VZ8                 3.25  3.25  2.95
2008 BJ22                4.30  4.30  4.30
2021 AY8                 3.10  2.90  3.15
2009 FP8                 3.90  3.65  3.70
P/2017 FL36 (PANSTARRS)  2.80  2.75  2.75
2010 TR241               2.05  1.95  2.05
2002 CW116               2.95  2.90  3.05

In [13]:
# Load saved sweep outputs only; no database load or model training required.
import glob as globlib
import os

import pandas as pd
import paper_table
from IPython.display import display

RUN_NAME = "table3_seed_sweep"
OUTPUT_DIR = os.path.join("multi_run_outputs", RUN_NAME)
NOTES_CSV = "table_notes.csv"
PM_COLUMNS = ["prob", "DeltaQ", "S_EV", "DeltaH"]
PM_DECIMALS = {"prob": 6, "DeltaQ": 1, "S_EV": 5, "DeltaH": 2, "exp_Num_opps": 1}
TABLE_VALUE_COLS = paper_table.DATA_COLUMNS + ["DeltaH"]
table_notes = paper_table.load_notes(NOTES_CSV)
for row in table_notes:
    row["h_marker"] = row.get("h_marker") or ""
table_order = [row["designation"] for row in table_notes]

run_files = sorted(globlib.glob(os.path.join(OUTPUT_DIR, "run_*_table_rows.csv")))
if not run_files:
    raise FileNotFoundError(f"No saved run tables found in {OUTPUT_DIR}")

all_runs = pd.concat((pd.read_csv(path) for path in run_files), ignore_index=True)
n_runs_done = all_runs["run"].nunique()
stats = (all_runs.groupby("designation")[TABLE_VALUE_COLS]
         .agg(["mean", "std", "median", "min", "max", "count"])
         .reindex(table_order))
stats.to_csv(os.path.join(OUTPUT_DIR, "table3_run_statistics.csv"))

summary = pd.DataFrame(index=table_order)
for column in TABLE_VALUE_COLS:
    summary[column] = stats[(column, "mean")]
    if column in PM_COLUMNS:
        summary[column + " +/-"] = stats[(column, "std")]

print(f"Loaded {n_runs_done} completed runs from {OUTPUT_DIR}")
display(summary)

Loaded 3 completed runs from multi_run_outputs/table3_seed_sweep

,q,a,e,i,TJ,H,Num_opps,exp_Num_opps,prob,prob +/-,DeltaQ,DeltaQ +/-,S_EV,S_EV +/-,DeltaH,DeltaH +/-
2010 RH69,4.276048,4.532396,0.056559,11.54822,2.973910,13.95,3.0,18.362625,0.999998,2.046194e-06,11.367557,0.560582,4.872054e-06,1.139392e-07,2.450000,0.000000
362P/(457175) 2008 GO98,2.864301,3.971173,0.278727,15.55983,2.926730,12.91,7.0,23.955757,0.999998,2.121001e-06,10.326086,0.272304,2.899841e-05,1.032173e-06,3.250000,0.000000
282P/(323137) 2003 BM80,3.438718,4.234372,0.187904,5.81319,2.991756,13.62,7.0,22.028741,0.999998,2.046835e-06,10.316230,0.262152,1.211888e-04,6.985267e-06,2.100000,0.000000
2017 QN84,2.474881,3.769087,0.343374,12.07147,2.943831,14.97,4.0,12.836535,0.999998,7.932139e-07,5.078355,0.053134,2.606914e-03,2.484737e-04,2.033333,0.028868
2008 VK110,4.436583,7.167172,0.380986,7.38588,2.878252,13.75,3.0,7.542647,0.987351,6.581392e-03,-0.151789,0.014297,4.258534e-02,1.138876e-02,1.333333,0.510718
2001 BV70,2.063079,3.593632,0.425907,4.33032,2.947403,15.14,1.0,15.953092,0.999999,4.520722e-07,10.967493,0.040507,3.224969e-07,4.305986e-08,4.416667,0.152753
P/2025 UX109 (Ye),2.569961,3.806430,0.324837,3.18090,2.982290,15.00,1.0,16.715579,0.999999,3.884326e-07,11.924029,0.047092,1.503797e-07,1.957071e-08,4.550000,0.050000
2019 OE31,3.942522,4.381322,0.100152,5.22115,3.006031,14.64,1.0,16.764423,0.999998,2.594039e-06,11.893297,0.058024,1.424757e-07,4.471353e-09,3.583333,0.251661
2018 BJ11,3.252873,4.200594,0.225616,3.43068,2.986205,15.55,1.0,10.351398,0.999991,1.238513e-05,5.006042,0.009696,8.690481e-05,4.019807e-06,3.300000,0.180278
P/2022 BV9 (Lemmon),3.347685,4.366555,0.233335,11.92230,2.934749,13.79,1.0,18.580412,0.999991,7.536389e-06,14.014337,0.000353,2.323031e-08,2.017759e-09,4.250000,0.346410
489P/Denning,1.561006,4.421537,0.646954,4.02690,2.579142,15.35,1.0,8.512345,0.999756,1.514734e-04,3.082958,0.102002,5.628439e-04,1.643822e-04,3.850000,0.086603
2024 XE22,4.535879,5.865080,0.226630,27.16003,2.727256,14.26,1.0,6.303197,0.989881,4.224246e-03,1.518805,0.352830,5.021306e-03,8.079003e-04,3.616667,0.585947
2009 DP2,3.822559,6.646579,0.424883,26.76899,2.609808,14.17,1.0,5.377837,0.951474,1.570915e-02,0.820981,0.435785,1.256363e-02,6.424361e-04,4.250000,0.173205
P/2023 JN16 (Lemmon),2.300095,2.697442,0.147305,3.70130,3.350239,15.73,1.0,19.689926,1.000000,4.466049e-07,15.014401,0.000065,7.646364e-09,3.984996e-10,4.483333,0.175594
2025 HV38,2.366069,2.484172,0.047542,7.24007,3.463847,15.42,1.0,21.093904,1.000000,1.704010e-07,16.113070,0.108429,1.878059e-09,9.569957e-11,5.166667,0.057735
2015 BC566,2.951045,3.063210,0.036617,11.68986,3.200295,16.33,1.0,13.652472,1.000000,1.214654e-07,9.005206,0.002382,3.201364e-06,1.290347e-07,2.966667,0.152753
2007 VB146,2.439879,2.752892,0.113703,3.49271,3.332674,16.94,1.0,14.815995,0.999999,2.458357e-07,9.994027,0.013812,9.995745e-07,1.322646e-08,2.600000,0.086603
2025 VZ8,2.394910,2.620616,0.086127,12.10031,3.368118,16.76,1.0,12.597596,0.999999,7.235275e-07,7.208795,0.116150,9.190318e-06,2.442653e-07,3.150000,0.173205
2008 BJ22,2.942906,3.073201,0.042397,11.51245,3.197832,15.20,1.0,20.564187,0.999999,4.803497e-07,16.014377,0.000315,3.192627e-09,2.303448e-10,4.300000,0.000000
2021 AY8,2.567449,2.722797,0.057054,5.00731,3.349841,17.52,1.0,12.343930,0.999998,6.769771e-07,6.980863,0.039246,1.185256e-05,6.425259e-07,3.050000,0.132288
2009 FP8,2.477724,3.014208,0.177985,4.62744,3.219233,16.94,1.0,11.788925,0.999997,1.266773e-06,6.300940,0.461654,2.063891e-05,8.745377e-07,3.750000,0.132288
P/2017 FL36 (PANSTARRS),2.828733,2.927577,0.033763,15.69930,3.220676,16.65,1.0,9.541052,0.999980,1.161179e-05,4.107223,0.045016,1.958222e-04,1.800177e-05,2.766667,0.028868
2010 TR241,2.746025,3.050750,0.099885,12.41983,3.193626,16.97,1.0,10.591459,0.999993,8.913722e-06,5.310132,0.520522,6.848411e-05,5.997363e-06,2.016667,0.057735
2002 CW116,2.068204,2.690282,0.231232,8.13852,3.319074,17.52,1.0,9.165663,0.999899,2.866724e-05,3.776472,0.243793,2.843401e-04,8.836707e-06,2.966667,0.076376

In [14]:
# LaTeX Table 3: retain committed table3.tex's text, symbols, layout, notes, and RH69 orbital elements; update model values with mean +/- standard deviation.
import glob
import os

import pandas as pd
import paper_table

RUN_NAME = "table3_seed_sweep"
OUTPUT_DIR = os.path.join("multi_run_outputs", RUN_NAME)
NOTES_CSV = "table_notes.csv"
PM_COLUMNS = ["prob", "DeltaQ", "S_EV", "DeltaH"]
PM_DECIMALS = {"prob": 6, "DeltaQ": 1, "S_EV": 5, "DeltaH": 1, "exp_Num_opps": 1}
TABLE_VALUE_COLS = paper_table.DATA_COLUMNS + ["DeltaH"]


old_order = False  # same meaning as in paper_table.build_table
include_plus_minus = False


run_files = sorted(glob.glob(os.path.join(OUTPUT_DIR, "run_*_table_rows.csv")))
if not run_files:
    raise FileNotFoundError(f"No saved run tables found in {OUTPUT_DIR}")
all_runs = pd.concat((pd.read_csv(path) for path in run_files), ignore_index=True)
n_runs_done = all_runs["run"].nunique()

table_notes = paper_table.load_notes(NOTES_CSV)
for row in table_notes:
    row["h_marker"] = row.get("h_marker") or ""
table_order = [row["designation"] for row in table_notes]
stats = (all_runs.groupby("designation")[TABLE_VALUE_COLS]
         .agg(["mean", "std", "median", "min", "max", "count"])
         .reindex(table_order))
stats.to_csv(os.path.join(OUTPUT_DIR, "table3_run_statistics.csv"))

PM_LATEX = {"prob": r"$P(N_{\rm opp}\ge4)$", "DeltaQ": r"$\Delta Q$", "S_EV": r"$S_{\rm EV}$",
            "DeltaH": r"$\Delta H$", "exp_Num_opps": r"$E[N_{\rm opp}]$"}
COMMITTED_ORBIT_VALUES = {"2010 RH69": ["3.90", "4.27", "0.087", "11.92"]}


def fmt_value(col, mean, std, count):
    if col in PM_DECIMALS:
        text = "" if pd.isna(mean) else f"{mean:.{PM_DECIMALS[col]}f}"
    else:
        text = paper_table.FORMATTERS[col](mean)
    if include_plus_minus and col in PM_COLUMNS and text and count > 1 and not pd.isna(std):
        text += rf" $\pm$ {std:.{PM_DECIMALS.get(col, 2)}f}"
    return text


def render_row(r, s):
    obj = paper_table.format_designation(r["designation"], r["confirmed"]) + r["marker"]
    cells = [fmt_value(c, s[(c, "mean")], s[(c, "std")], s[(c, "count")]) for c in TABLE_VALUE_COLS]
    if r["designation"] in COMMITTED_ORBIT_VALUES:
        cells[:4] = COMMITTED_ORBIT_VALUES[r["designation"]]
    h_index = TABLE_VALUE_COLS.index("H")
    cells[h_index] = (cells[h_index] or "") + r["h_marker"]
    if r["nopp_dagger"]:
        i = TABLE_VALUE_COLS.index("Num_opps")
        cells[i] = (cells[i] or "") + paper_table._DAGGER
    cells = [c if c else "  " for c in cells]
    return f"\\objectcell{{{obj}}} &\n" + " & ".join(cells) + f" &\n{r['note']} \\\\" 


# paper_table's header/footer plus the Delta-H column (as in table3.tex) and a note on the +/- values
header = paper_table._HEADER
header = header.replace("{lrrrrrrrrrrrl}", "{lrrrrrrrrrrrrl}")
linebreak = "\\" * 2
header = header.replace(
    r"Note " + linebreak,
    r"$\Delta H$\tabnote{\revision{Magnitude offset required to explain anomaly such that with this offset the dimmer $H_V$ would yield $E[N_{\rm opp}]$ within 0.5 of actual $N_{\rm opp}$.}}&" + "\n" + r"Note " + linebreak,
    1,
)
header = header.replace(r"$S_{\rm EV}$\textsuperscript{g} & Note " + linebreak,
                        r"$S_{\rm EV}$\textsuperscript{g} & $\Delta H$\textsuperscript{h} & Note " + linebreak)
header = header.replace(r"\multicolumn{13}", r"\multicolumn{14}")

footer = paper_table._FOOTER.replace(r"\multicolumn{13}", r"\multicolumn{14}")
committed_h_note = (r"\multicolumn{14}{l}{\footnotesize $^{\S}$\,\revision{A multi-opposition object with significant differences in $H_V$ across oppositions. We use the brightest $H_V$.}}"
                    + linebreak + "\n")
footer = footer.replace(r"\printtabnotes", committed_h_note + r"\printtabnotes")
if include_plus_minus:
    pm_names = [PM_LATEX.get(c, c) for c in PM_COLUMNS]
    pm_list = ", ".join(pm_names[:-1]) + ", and " + pm_names[-1] if len(pm_names) > 1 else pm_names[0]
    pm_note = (r"\multicolumn{14}{l}{\footnotesize " + pm_list + r": mean $\pm$ standard deviation over "
               + f"{n_runs_done}" + r" training runs with different cross-validation folds and model seeds.}" + linebreak + "\n")
    assert footer.count(r"\printtabnotes") == 1
    footer = footer.replace(r"\printtabnotes", pm_note + r"\printtabnotes")

multi, single, asteroid = [], [], []
for r in table_notes:
    s = stats.loc[r["designation"]]
    if r["group"] == "cometary":
        nopp = s[("Num_opps", "mean")]
        (multi if (not pd.isna(nopp) and nopp > 1) else single).append((r, s))
    else:
        asteroid.append((r, s))

if not old_order:
    multi.sort(key=lambda e: paper_table._key_asc(e[1][("S_EV", "mean")]))
    single.sort(key=lambda e: paper_table._key_desc(e[1][("prob", "mean")]))
    asteroid.sort(key=lambda e: paper_table._key_desc(e[1][("prob", "mean")]))

parts = [header]
for label, entries, sortcap, newpage in [
    (paper_table.SECTION_MULTI_COMET, multi, paper_table._SORT_SEV_ASC, False),
    (paper_table.SECTION_SINGLE_COMET, single, paper_table._SORT_PROB_DESC, False),
    (paper_table.SECTION_ASTEROID, asteroid, paper_table._SORT_PROB_DESC, True),
]:
    if not entries:
        continue
    if newpage:
        parts.append(r"\newpage")
    parts.append(f"\\multicolumn{{14}}{{l}}{{\\textbf{{{label}}} \\textnormal{{\\footnotesize ({sortcap})}}}}\\\\")
    parts.append(r"\midrule")
    parts.append("")
    for r, s in entries:
        parts.append(render_row(r, s))
        parts.append("")
    parts.append(r"\midrule")
if parts[-1] == r"\midrule":
    parts.pop()
parts.append(footer)
latex_multi = "\n".join(parts)

table_path = os.path.join(OUTPUT_DIR, "table3_multi_run.tex")
with open(table_path, "w") as f:
    f.write(latex_multi)
print(f"written to {table_path}\n")
print(latex_multi)

written to multi_run_outputs/table3_seed_sweep/table3_multi_run.tex

\begin{longrotatetable}

\begin{longtable}{lrrrrrrrrrrrrl}
\caption{\activityscope\ discoveries, independent recoveries, and candidates. Objects with observed activity are marked with an asterisk.}
\label{tab:activityscope_results}\\
\toprule
Object & $q$ {\footnotesize (au)} & $a$ {\footnotesize (au)} & $e$ & $i~(^\circ)$ &
$T_J$\tabnote{Tisserand parameter with respect to Jupiter.} &
$H_V$\tabnote{Absolute magnitude in the $V$ band, assuming an inert object.} &
$N_{\rm opp}$\tabnote{Number of oppositions on which the object has been observed.} &
{\footnotesize $E[N_{\rm opp}]$}\tabnote{Expected number of observed oppositions for an inert object of the same orbit and $H_V$, predicted by the regression model.} &
{\footnotesize $P(N_{\rm opp}\ge4)$}\tabnote{Binary-classifier probability that an inert object of the same orbit and $H_V$ would be observed on at least four oppositions.} &
$\Delta Q$\tabnote{Quantile deficit $\Delta Q = Q_{0.006} - N_{\rm opp}$, where $Q_{0.006}$ is the model's $0.006$-quantile prediction of the opposition count. Larger positive values indicate a larger deficit.} &
$S_{\rm EV}$\tabnote{Poisson lower-tail anomaly score $S_{\rm EV}=F_{\rm Pois}(N_{\rm opp}-1;\,E[N_{\rm opp}]-1)$. Smaller values indicate a larger deficit relative to $E[N_{\rm opp}]$.} &
$\Delta H$\tabnote{\revision{Magnitude offset required to explain anomaly such that with this offset the dimmer $H_V$ would yield $E[N_{\rm opp}]$ within 0.5 of actual $N_{\rm opp}$.}}&
Note \\
\midrule
\endfirsthead

\caption[]{\activityscope\ discoveries, independent recoveries, and candidates. Objects with observed activity are marked with an asterisk. \mbox{(continued)}}\\
\toprule
Object & $q$ {\footnotesize (au)} & $a$ {\footnotesize (au)} & $e$ & $i~(^\circ)$ &
$T_J$\textsuperscript{a} & $H_V$\textsuperscript{b} & $N_{\rm opp}$\textsuperscript{c} &
{\footnotesize $E[N_{\rm opp}]$}\textsuperscript{d} & {\footnotesize $P(N_{\rm opp}\ge4)$}\textsuperscript{e} &
$\Delta Q$\textsuperscript{f} & $S_{\rm EV}$\textsuperscript{g} & $\Delta H$\textsuperscript{h} & Note \\
\midrule
\endhead

\midrule
\multicolumn{14}{r}{Continued on next page}\\
\endfoot

\endlastfoot

\multicolumn{14}{l}{\textbf{Cometary orbits (multiple oppositions when flagged)} \textnormal{\footnotesize (sorted by $S_{\rm EV}$, ascending)}}\\
\midrule

\objectcell{2010~RH$_{69}$$^{\ast}$$^{\ddag}$} &
3.90 & 4.27 & 0.087 & 11.92 & 2.97 & 13.9 & 3 & 18.4 & 0.999998 & 11.4 & 0.00000 & 2.5 &
\notecell{Comet independently re-flagged by this work} \\

\objectcell{362P/(457175) 2008~GO$_{98}$$^{\ast}$} &
2.86 & 3.97 & 0.279 & 15.56 & 2.93 & 12.9 & 7 & 24.0 & 0.999998 & 10.3 & 0.00003 & 3.2 &
\notecell{\citet{2017CBET.4411....1L}} \\

\objectcell{282P/(323137) 2003~BM$_{80}$$^{\ast}$} &
3.44 & 4.23 & 0.188 & 5.81 & 2.99 & 13.6 & 7 & 22.0 & 0.999998 & 10.3 & 0.00012 & 2.1 &
\notecell{\citet{2022ApJ...937L...2C,chandlerActiveAsteroidsCitizen2024}} \\

\objectcell{2017~QN$_{84}$$^{\ast}$} &
2.47 & 3.77 & 0.343 & 12.07 & 2.94 & 15.0 & 4 & 12.8 & 0.999998 & 5.1 & 0.00261 & 2.0 &
\notecell{\citet{chandlerActiveAsteroidsCitizen2024,2025epsc.conf.1661F}} \\

\objectcell{2008~VK$_{110}$$^{\Vert}$} &
4.44 & 7.17 & 0.381 & 7.39 & 2.88 & 13.8$^{\S}$ & 3 & 7.5 & 0.987351 & -0.2 & 0.04259 & 1.3 &
\notecell{Identified by \activityscope{}; Possible morphologic confirmation; Brightness varies across oppositions} \\

\midrule
\multicolumn{14}{l}{\textbf{Cometary orbits (single opposition when flagged)} \textnormal{\footnotesize (sorted by $P(N_{\rm opp}\ge4)$, descending)}}\\
\midrule

\objectcell{2001~BV$_{70}$} &
2.06 & 3.59 & 0.426 & 4.33 & 2.95 & 15.1 & 1 & 16.0 & 0.999999 & 11.0 & 0.00000 & 4.4 &
\notecell{High-confidence candidate; archival confirmation unavailable} \\

\objectcell{P/2025~UX$_{109}$ (Ye)$^{\ast}$} &
2.57 & 3.81 & 0.325 & 3.18 & 2.98 & 15.0 & 1 & 16.7 & 0.999999 & 11.9 & 0.00000 & 4.5 &
\notecell{Independent identification by \activityscope\tabnote{P. VanWylen, \url{https://groups.io/g/comets-ml/message/34359}.}} \\

\objectcell{2019~OE$_{31}$$^{\ast}$} &
3.94 & 4.38 & 0.100 & 5.22 & 3.01 & 14.6 & 1 & 16.8 & 0.999998 & 11.9 & 0.00000 & 3.6 &
\notecell{\citet{oldroydCometaryActivityDiscovered2023}} \\

\objectcell{P/2022~BV$_{9}$ (Lemmon)$^{\ast}$} &
3.35 & 4.37 & 0.233 & 11.92 & 2.93 & 13.8 & 1$^{\dagger}$ & 18.6 & 0.999991 & 14.0 & 0.00000 & 4.2 &
\notecell{Identified by \activityscope\tabnote{P. VanWylen, \url{https://groups.io/g/comets-ml/message/31369}.}} \\

\objectcell{2018~BJ$_{11}$$^{\ast}$} &
3.25 & 4.20 & 0.226 & 3.43 & 2.99 & 15.6 & 1 & 10.4 & 0.999991 & 5.0 & 0.00009 & 3.3 &
\notecell{Independent identification; Activity visible in archival imagery\tabnote{This object was on the Possible Comet Confirmation Page prior to our reconfirmation and discovery of archival imagery.}} \\

\objectcell{489P/Denning$^{\ast}$} &
1.56 & 4.42 & 0.647 & 4.03 & 2.58 & 15.3 & 1$^{\dagger}$ & 8.5 & 0.999756 & 3.1 & 0.00056 & 3.9 &
\notecell{Recovered after 130 yr; initial identification by \activityscope\tabnote{P. VanWylen, \url{https://groups.io/g/comets-ml/message/32365}.}} \\

\objectcell{2024~XE$_{22}$$^{\ast}$} &
4.54 & 5.87 & 0.227 & 27.16 & 2.73 & 14.3 & 1$^{\dagger}$ & 6.3 & 0.989881 & 1.5 & 0.00502 & 3.6 &
\notecell{Identified by \activityscope{}; activity observed in 2025 November} \\

\objectcell{2009~DP$_{2}$$^{\ast}$} &
3.82 & 6.65 & 0.425 & 26.77 & 2.61 & 14.2$^{\S}$ & 1$^{\dagger}$ & 5.4 & 0.951474 & 0.8 & 0.01256 & 4.2 &
\notecell{Identified by \activityscope{}; recovered active in 2026} \\

\midrule
\newpage
\multicolumn{14}{l}{\textbf{Asteroidal orbits} \textnormal{\footnotesize (sorted by $P(N_{\rm opp}\ge4)$, descending)}}\\
\midrule

\objectcell{P/2023~JN$_{16}$ (Lemmon)$^{\ast}$} &
2.30 & 2.70 & 0.147 & 3.70 & 3.35 & 15.7 & 1$^{\dagger}$ & 19.7 & 1.000000 & 15.0 & 0.00000 & 4.5 &
\notecell{Initial identification by \activityscope\tabnote{P. VanWylen, \url{https://groups.io/g/mpml/message/38758}.}; \citet{2024MPEC....Q....4.,2024CBET.5430....1A,2024DPS....5620804T,2025epsc.conf..471A,2025AcA....75..343B}} \\

\objectcell{2015~BC$_{566}$$^{\ast}$} &
2.95 & 3.06 & 0.037 & 11.69 & 3.20 & 16.3 & 1 & 13.7 & 1.000000 & 9.0 & 0.00000 & 3.0 &
\notecell{Identified by \activityscope; Active in DECam and MegaCam} \\

\objectcell{2025~HV$_{38}$} &
2.37 & 2.48 & 0.048 & 7.24 & 3.46 & 15.4 & 1 & 21.1 & 1.000000 & 16.1 & 0.00000 & 5.2 &
\notecell{Exceptionally strong candidate; not yet morphologically confirmed; not observed in 2026 despite $V \approx 18.3$} \\

\objectcell{2008~BJ$_{22}$$^{\ast}$} &
2.94 & 3.07 & 0.042 & 11.51 & 3.20 & 15.2 & 1 & 20.6 & 0.999999 & 16.0 & 0.00000 & 4.3 &
\notecell{Initial identification by \activityscope\tabnote{S. Deen, \url{https://groups.io/g/comets-ml/message/31013}.}; \citet{2023RNAAS...7...48D}} \\

\objectcell{2007~VB$_{146}$} &
2.44 & 2.75 & 0.114 & 3.49 & 3.33 & 16.9 & 1 & 14.8 & 0.999999 & 10.0 & 0.00000 & 2.6 &
\notecell{Negative archival recovery; very high confidence candidate} \\

\objectcell{2025~VZ$_{8}$$^{\ast}$} &
2.39 & 2.62 & 0.086 & 12.10 & 3.37 & 16.8 & 1 & 12.6 & 0.999999 & 7.2 & 0.00001 & 3.1 &
\notecell{Initial identification by \activityscope\tabnote{P. VanWylen, \url{https://groups.io/g/mpml/message/41136}.}; \citet{2026RNAAS..10....1H}} \\

\objectcell{2021~AY$_{8}$$^{\ast}$} &
2.57 & 2.72 & 0.057 & 5.01 & 3.35 & 17.5 & 1$^{\dagger}$ & 12.3 & 0.999998 & 7.0 & 0.00001 & 3.1 &
\notecell{Identified by \activityscope; Confirmed active in DECam and Pan-STARRS archives} \\

\objectcell{2009~FP$_{8}$} &
2.48 & 3.01 & 0.178 & 4.63 & 3.22 & 16.9 & 1 & 11.8 & 0.999997 & 6.3 & 0.00002 & 3.8 &
\notecell{Negative archival recovery; very high confidence candidate} \\

\objectcell{2010~TR$_{241}$} &
2.75 & 3.05 & 0.100 & 12.42 & 3.19 & 17.0 & 1 & 10.6 & 0.999993 & 5.3 & 0.00007 & 2.0 &
\notecell{Negative archival recovery; high confidence candidate} \\

\objectcell{P/2017~FL$_{36}$ (PANSTARRS)$^{\ast}$} &
2.83 & 2.93 & 0.034 & 15.70 & 3.22 & 16.6 & 1 & 9.5 & 0.999980 & 4.1 & 0.00020 & 2.8 &
\notecell{Initial identification by \activityscope\tabnote{P. VanWylen, \url{https://groups.io/g/comets-ml/message/33447}.}; \citet{2025CBET.5551....1L,2025MPEC....H...86C}} \\

\objectcell{2002~CW$_{116}$$^{\ast}$} &
2.07 & 2.69 & 0.231 & 8.14 & 3.32 & 17.5 & 1 & 9.2 & 0.999899 & 3.8 & 0.00028 & 3.0 &
\notecell{Identified by \activityscope; confirmed active in SDSS archives\tabnote{P. VanWylen, S. Deen \url{https://groups.io/g/mpml/topic/104468465}}} \\

\bottomrule
\multicolumn{14}{l}{\footnotesize Unless otherwise noted, all orbital elements are osculating elements from the epoch provided in \texttt{MPCORB}.}\\
\multicolumn{14}{l}{\footnotesize $^{\ast}$\,Observationally confirmed active object.}\\
\multicolumn{14}{l}{\footnotesize $^{\Vert}$\,Activity supported by combination of observational and photometric evidence.}\\
\multicolumn{14}{l}{\footnotesize $^{\dagger}$\,Single-opposition at the time of flagging; tabulated $N_{\rm opp}$, $\Delta Q$, and $S_{\rm EV}$ are the values the model assigns to an otherwise-identical single-opposition object.}\\
\multicolumn{14}{l}{\footnotesize $^{\ddag}$\,Indicates that provided orbital information is from osculating elements taken from the discovery epoch instead of latest available epoch.}\\
\multicolumn{14}{l}{\footnotesize $^{\S}$\,\revision{A multi-opposition object with significant differences in $H_V$ across oppositions. We use the brightest $H_V$.}}\\
\printtabnotes

\end{longtable}

\end{longrotatetable}

In [15]:
# Compact anomaly-metric table, sorted by mean Delta Q (descending).
import glob
import os

import pandas as pd
import paper_table

RUN_NAME = "table3_seed_sweep"
OUTPUT_DIR = os.path.join("multi_run_outputs", RUN_NAME)
NOTES_CSV = "table_notes.csv"
METRICS = ["prob", "DeltaQ", "S_EV", "DeltaH"]
DECIMALS = {"prob": 6, "DeltaQ": 1, "S_EV": 5, "DeltaH": 1}
METRIC_HEADERS = [r"$P(N_{\rm opp}\ge4)$", r"$\Delta Q$", r"$S_{\rm EV}$", r"$\Delta H$"]

run_files = sorted(glob.glob(os.path.join(OUTPUT_DIR, "run_*_table_rows.csv")))
if not run_files:
    raise FileNotFoundError(f"No saved run tables found in {OUTPUT_DIR}")
all_runs = pd.concat((pd.read_csv(path) for path in run_files), ignore_index=True)
table_notes = paper_table.load_notes(NOTES_CSV)

stats = all_runs.groupby("designation")[METRICS].agg(["mean", "std", "count"])
rows = []
for note in table_notes:
    designation = note["designation"]
    if designation not in stats.index:
        continue
    row_stats = stats.loc[designation]
    delta_q = row_stats[("DeltaQ", "mean")]
    if pd.isna(delta_q):
        continue
    values = []
    for metric in METRICS:
        mean = row_stats[(metric, "mean")]
        std = row_stats[(metric, "std")]
        count = row_stats[(metric, "count")]
        if pd.isna(mean):
            values.append("")
        elif count > 1 and not pd.isna(std):
            values.append(rf"{mean:.{DECIMALS[metric]}f} $\pm$ {std:.{DECIMALS[metric]}f}")
        else:
            values.append(f"{mean:.{DECIMALS[metric]}f}")
    rows.append((delta_q, paper_table.format_designation(designation, note["confirmed"]), values))

rows.sort(key=lambda row: row[0], reverse=True)
latex_lines = [
    r"\begin{table}",
    r"\centering",
    r"\caption{ActivitySCOPE anomaly metrics, sorted by decreasing $\Delta Q$.}",
    r"\label{tab:activityscope_anomaly_metrics}",
    r"\small",
    r"\begin{tabular}{lrrrr}",
    r"\toprule",
    "Object & " + " & ".join(METRIC_HEADERS) + r" \\",
    r"\midrule",
]
for _, designation, values in rows:
    latex_lines.append(designation + " & " + " & ".join(values) + r" \\")
latex_lines.extend([
    r"\bottomrule",
    r"\end{tabular}",
    r"\end{table}",
])

compact_table = "\n".join(latex_lines)
compact_table_path = os.path.join(OUTPUT_DIR, "table3_anomaly_metrics.tex")
with open(compact_table_path, "w") as file:
    file.write(compact_table)
print(f"written to {compact_table_path}\n")
print(compact_table)

written to multi_run_outputs/table3_seed_sweep/table3_anomaly_metrics.tex

\begin{table}
\centering
\caption{ActivitySCOPE anomaly metrics, sorted by decreasing $\Delta Q$.}
\label{tab:activityscope_anomaly_metrics}
\small
\begin{tabular}{lrrrr}
\toprule
Object & $P(N_{\rm opp}\ge4)$ & $\Delta Q$ & $S_{\rm EV}$ & $\Delta H$ \\
\midrule
2025~HV$_{38}$ & 1.000000 $\pm$ 0.000000 & 16.1 $\pm$ 0.1 & 0.00000 $\pm$ 0.00000 & 5.2 $\pm$ 0.1 \\
2008~BJ$_{22}$$^{\ast}$ & 0.999999 $\pm$ 0.000000 & 16.0 $\pm$ 0.0 & 0.00000 $\pm$ 0.00000 & 4.3 $\pm$ 0.0 \\
P/2023~JN$_{16}$ (Lemmon)$^{\ast}$ & 1.000000 $\pm$ 0.000000 & 15.0 $\pm$ 0.0 & 0.00000 $\pm$ 0.00000 & 4.5 $\pm$ 0.2 \\
P/2022~BV$_{9}$ (Lemmon)$^{\ast}$ & 0.999991 $\pm$ 0.000008 & 14.0 $\pm$ 0.0 & 0.00000 $\pm$ 0.00000 & 4.2 $\pm$ 0.3 \\
P/2025~UX$_{109}$ (Ye)$^{\ast}$ & 0.999999 $\pm$ 0.000000 & 11.9 $\pm$ 0.0 & 0.00000 $\pm$ 0.00000 & 4.5 $\pm$ 0.0 \\
2019~OE$_{31}$$^{\ast}$ & 0.999998 $\pm$ 0.000003 & 11.9 $\pm$ 0.1 & 0.00000 $\pm$ 0.00000 & 3.6 $\pm$ 0.3 \\
2010~RH$_{69}$$^{\ast}$ & 0.999998 $\pm$ 0.000002 & 11.4 $\pm$ 0.6 & 0.00000 $\pm$ 0.00000 & 2.5 $\pm$ 0.0 \\
2001~BV$_{70}$ & 0.999999 $\pm$ 0.000000 & 11.0 $\pm$ 0.0 & 0.00000 $\pm$ 0.00000 & 4.4 $\pm$ 0.2 \\
362P/(457175) 2008~GO$_{98}$$^{\ast}$ & 0.999998 $\pm$ 0.000002 & 10.3 $\pm$ 0.3 & 0.00003 $\pm$ 0.00000 & 3.2 $\pm$ 0.0 \\
282P/(323137) 2003~BM$_{80}$$^{\ast}$ & 0.999998 $\pm$ 0.000002 & 10.3 $\pm$ 0.3 & 0.00012 $\pm$ 0.00001 & 2.1 $\pm$ 0.0 \\
2007~VB$_{146}$ & 0.999999 $\pm$ 0.000000 & 10.0 $\pm$ 0.0 & 0.00000 $\pm$ 0.00000 & 2.6 $\pm$ 0.1 \\
2015~BC$_{566}$$^{\ast}$ & 1.000000 $\pm$ 0.000000 & 9.0 $\pm$ 0.0 & 0.00000 $\pm$ 0.00000 & 3.0 $\pm$ 0.2 \\
2025~VZ$_{8}$$^{\ast}$ & 0.999999 $\pm$ 0.000001 & 7.2 $\pm$ 0.1 & 0.00001 $\pm$ 0.00000 & 3.1 $\pm$ 0.2 \\
2021~AY$_{8}$$^{\ast}$ & 0.999998 $\pm$ 0.000001 & 7.0 $\pm$ 0.0 & 0.00001 $\pm$ 0.00000 & 3.1 $\pm$ 0.1 \\
2009~FP$_{8}$ & 0.999997 $\pm$ 0.000001 & 6.3 $\pm$ 0.5 & 0.00002 $\pm$ 0.00000 & 3.8 $\pm$ 0.1 \\
2010~TR$_{241}$ & 0.999993 $\pm$ 0.000009 & 5.3 $\pm$ 0.5 & 0.00007 $\pm$ 0.00001 & 2.0 $\pm$ 0.1 \\
2017~QN$_{84}$$^{\ast}$ & 0.999998 $\pm$ 0.000001 & 5.1 $\pm$ 0.1 & 0.00261 $\pm$ 0.00025 & 2.0 $\pm$ 0.0 \\
2018~BJ$_{11}$$^{\ast}$ & 0.999991 $\pm$ 0.000012 & 5.0 $\pm$ 0.0 & 0.00009 $\pm$ 0.00000 & 3.3 $\pm$ 0.2 \\
P/2017~FL$_{36}$ (PANSTARRS)$^{\ast}$ & 0.999980 $\pm$ 0.000012 & 4.1 $\pm$ 0.0 & 0.00020 $\pm$ 0.00002 & 2.8 $\pm$ 0.0 \\
2002~CW$_{116}$$^{\ast}$ & 0.999899 $\pm$ 0.000029 & 3.8 $\pm$ 0.2 & 0.00028 $\pm$ 0.00001 & 3.0 $\pm$ 0.1 \\
489P/Denning$^{\ast}$ & 0.999756 $\pm$ 0.000151 & 3.1 $\pm$ 0.1 & 0.00056 $\pm$ 0.00016 & 3.9 $\pm$ 0.1 \\
2024~XE$_{22}$$^{\ast}$ & 0.989881 $\pm$ 0.004224 & 1.5 $\pm$ 0.4 & 0.00502 $\pm$ 0.00081 & 3.6 $\pm$ 0.6 \\
2009~DP$_{2}$$^{\ast}$ & 0.951474 $\pm$ 0.015709 & 0.8 $\pm$ 0.4 & 0.01256 $\pm$ 0.00064 & 4.2 $\pm$ 0.2 \\
2008~VK$_{110}$ & 0.987351 $\pm$ 0.006581 & -0.2 $\pm$ 0.0 & 0.04259 $\pm$ 0.01139 & 1.3 $\pm$ 0.5 \\
\bottomrule
\end{tabular}
\end{table}

In [17]:
# Semi-major-axis $a > 5.4$ list. Objects such as 2024 XE22, 2009 DP2, and
# 2008 VK110 may not appear in the main ranking, so search for these distant
# objects specifically rather than letting them get lost in the noise.

# This is the one thing that clearly benefits from the multi-run averaging.

extension_difficulty_threshold = 0.9
final_paths = sorted(glob.glob(os.path.join(OUTPUT_DIR, "run_*_final.parquet")))
if not final_paths:
    raise FileNotFoundError(f"No saved final frames found in {OUTPUT_DIR}")

final = pd.read_parquet(final_paths[-1])
default_col_set = [
    "prob", "prob_pessimistic", "prob_optimistic", "DeltaQ", "poisson_cdf",
    "extension_difficulty", "Num_opps", "quantile_Opps", "exp_Num_opps",
    "nights_total", "Ref", "Num_obs", "Arc_length", "U", "a", "i", "H",
    "q", "TJ",
]
display_columns = [column for column in default_col_set if column in final.columns]

final[((final["Arc_length"] >= 8) | (final["Arc_length"].isna()))
      & (final["Num_obs"] >= 6)
      & (final["a"] > 5.4)
      & (final["prob"] > 0.6)
      & (final["DeltaQ"] > -2.5)
      & ((final["extension_difficulty"].between(0, extension_difficulty_threshold))
         | (final["nights_total"].isna()))
      & (final["Orbital_period"] < 20)].sort_values(
          "poisson_cdf", ascending=True
      ).head(20)[display_columns]

,prob,DeltaQ,poisson_cdf,extension_difficulty,Num_opps,quantile_Opps,exp_Num_opps,nights_total,Ref,Num_obs,Arc_length,U,a,i,H,q,TJ
Principal_desig,,,,,,,,,,,,,,,,,
2024 XE22,0.985422,1.236687,0.005264,0.000179,1,2.236687,6.246905,10.0,MPO988022,36,22,4,5.86508,27.16003,14.26,4.535879,2.727256
2009 DP2,0.958636,0.998475,0.013030,0.000062,1,1.998475,5.340486,19.0,E2026-N01,79,22,2,6.646579,26.76899,14.17,3.822559,2.609808
2025 DP63,0.675492,-0.000764,0.039161,0.018570,1,0.999236,4.240070,3.0,MPO913751,6,11,9,5.828698,7.68778,15.75,4.499112,2.935161
2022 QJ32,0.672601,-0.000764,0.042677,0.000060,1,0.999236,4.154088,17.0,E2023-P46,71,189,4,5.909191,40.65269,15.26,2.71035,2.240115
2008 VK110,0.980498,-0.135825,0.055612,0.000160,3,2.864175,7.149735,9.0,MPO791125,24,<NA>,4,7.167172,7.38588,13.75,4.436583,2.878252
2023 GC4,0.827758,-1.002331,0.109163,0.000366,2,0.997669,4.779186,16.0,E2024-R79,57,<NA>,3,6.396129,54.63139,14.70,2.680366,1.85821
2010 CM53,0.720150,-1.000442,0.177164,0.000138,2,0.999558,4.154988,13.0,E2024-A12,55,<NA>,1,5.819806,19.17617,15.71,2.485397,2.531455
2016 PW84,0.852646,-2.001664,0.214635,0.000013,3,0.998336,5.167040,13.0,MPO544895,49,<NA>,1,5.823954,14.52161,14.60,4.196552,2.860166
2016 LN8,0.999945,-0.860226,0.236378,0.000041,10,9.139774,13.069443,NaN,MPO985294,194,<NA>,0,5.768674,43.28628,12.88,5.375157,2.431344
2023 XM5,0.714945,-1.000764,0.242249,0.000062,2,0.999236,3.735732,9.0,MPO894290,31,<NA>,3,6.490445,36.86705,14.38,4.933028,2.536518
2013 FC45,0.825989,-2.000001,0.272769,0.000061,3,0.999999,4.776160,41.0,E2026-QB8,152,<NA>,0,5.834052,8.43962,15.64,2.749381,2.669941
2020 XV1,0.958445,-1.935023,0.307234,0.000049,4,2.064977,5.715609,51.0,MPO725010,130,<NA>,0,5.928974,6.98953,14.88,3.553615,2.819162
2007 VW266,0.695259,-2.0,0.472227,0.000200,3,1.000000,3.788386,19.0,MPO640036,101,<NA>,1,5.444343,108.34011,15.20,3.323334,0.362787